### ISSUE TITLE
Cantera/scons brew conflicts

### ISSUE THREAD

**Issue by simone-hochgreb** [Homebrew/homebrew-science#2170]
multiple conflicts with a detected version of macports. 

Removed all of Macports (not sure it is wise), but now still reporting problems when trying to brew cantera: 

brew install cantera --HEAD --with-matlab=/Applications/MATLAB_R2014a.app/
==> Installing cantera from homebrew/homebrew-science
==> Cloning https://github.com/cantera/cantera.git
Updating /Library/Caches/Homebrew/cantera--git
==> Checking out branch master
==> /usr/local/opt/scons/bin/scons build prefix=/usr/local/Cellar/cantera/HEAD python_package=new CC=/usr/bin/clang
==> /usr/local/opt/scons/bin/scons test
    - runCanteraTests.m.passed

*****************************
scons: *** [test_problems/finish_tests] One or more tests failed.
scons: building terminated because of errors.
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

**Comment by tdsmith** [comment]
Please post the link returned by `brew gist-logs cantera`; thanks.

**Comment by simone-hochgreb** [comment]
This is what it says: 
https://gist.github.com/b7f4fed16694b49b8822

**Comment by Gflat** [comment]
Any follow up on this?  I'm running into the same issue trying to install 2.2.0 on two different macs, each using Py 2.7, OSX 10.10.4.  Doesn't matter if the matlab target is 2015a or 2014b, same issue.  Error occurs with the default build and --HEAD.

**Comment by tdsmith** [comment]
Please post the link returned by `brew gist-logs cantera`; thanks. The error @simone-hochgreb describes is not apparent in their logs.

**Comment by Gflat** [comment]
edited my previous comment to include the gist.  the install passes ALL matlab related tests with the exception of runCanteraTests.m.passed

**Comment by tdsmith** [comment]
It looks like the error is related to sundials: https://gist.github.com/anonymous/9f64e649446792e7c8ff#file-03-scons-L829-L878

If I install sundials, I see:
```
tim@rocketman:po_emails$ otool -L /usr/local/Cellar/sundials/2.5.0/lib/libsundials_cvodes.2.0.0.dylib
/usr/local/Cellar/sundials/2.5.0/lib/libsundials_cvodes.2.0.0.dylib:
	/usr/local/lib/libsundials_cvodes.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

which seems to be the right version.

What do you get if you run `otool -L /usr/local/lib/libsundials_cvodes.2.dylib`?

**Comment by Gflat** [comment]
Here is the output:

```
/usr/local/lib/libsundials_cvodes.2.dylib:
	/usr/local/lib/libsundials_cvodes.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

**Comment by tdsmith** [comment]
That's upsetting. Do you have any LD_ environment variables defined? (`set | grep LD_`)

**Comment by Gflat** [comment]
I have one.

```
set | grep LD_
DYLD_LIBRARY_PATH=/opt/intel/composer_xe_2013_sp1.2.139/compiler/lib/
```

**Comment by tdsmith** [comment]
Can you try unsetting DYLD_LIBRARY_PATH temporarily with `unset DYLD_LIBRARY_PATH` before installing cantera?

**Comment by Gflat** [comment]
I can try it, but system A had that path and system B had no path ... same errors out of brewing.

**Comment by tdsmith** [comment]
Can you post logs from a build where that wasn't set? I just want to be very sure it's the same error mechanism because it seems pretty wacky.

**Comment by Gflat** [comment]
https://gist.github.com/e64d4d3286dd90668b5a

there are the logs for the other system (one w/o intel compilers)

**Comment by tdsmith** [comment]
Okay, thanks. Can you verify that `otool -L /usr/local/lib/libsundials_cvodes.2.dylib` gives the same output (i.e. `(compatibility version 3.0.0, current version 3.0.0)`) on that system?

**Comment by Gflat** [comment]
From the second system:

```
otool -L /usr/local/lib/libsundials_cvodes.2.dylib
/usr/local/lib/libsundials_cvodes.2.dylib:
/usr/local/lib/libsundials_cvodes.2.dylib (compatibility version 3.0.0, current version 3.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by tdsmith** [comment]
I'm running out of ideas. The dynamic linker is throwing an error because it thinks the library it's trying to link to is the wrong version, even though the library appears to actually be the version that the linker thinks it wants.

MATLAB doesn't ship a copy of this, does it? I assume `find /Applications/MATLAB_R2014a.app -name *cvodes*` doesn't return anything? Do you see any other copies of the library elsewhere on your systems?

**Comment by Gflat** [comment]
Only have access to the first system for the moment, but it appears that MATLAB does indeed ship with it's own versions of the libraries.
```
find /Applications/MATLAB_R2014b.app -name *cvodes*
/Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.2.0.0.dylib
/Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.2.dylib
/Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.dylib
```

**Comment by Gflat** [comment]
otool output from the MATLAB libraries:
```
otool -L /Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.2.dylib
/Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.2.dylib:
	@rpath/libsundials_cvodes.2.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
```

**Comment by tdsmith** [comment]
Well, that'll do it; MATLAB is probably setting a DYLD_ variable (or equivalent) to prefer its bundled library versions, even though we would rather it didn't.

Can you ask the Cantera developers for help resolving this?

**Comment by jthwang** [comment]
Here's the output from the second system

find /Applications/MATLAB_R2014b.app -name *cvodes*
/Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.2.0.0.dylib
/Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.2.dylib
/Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.dylib

otool -L /Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.2.dylib
/Applications/MATLAB_R2014b.app/bin/maci64/libsundials_cvodes.2.dylib:
	@rpath/libsundials_cvodes.2.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)

**Comment by tdsmith** [comment]
You may also find it helpful to reach out to Mathworks yourself.

**Comment by speth** [comment]
I believe this issue was resolved by c7327d96.

**Comment by dpo** [comment]
All the formulae mentioned here have been updated, so I'll close this. Please open a new issue if problems persist. Thank you.
