### ISSUE TITLE
genometools fails test

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2187]
```
brew test genometools
Testing genometools
==> /bio/linuxbrew/Cellar/genometools/1.5.3/bin/gt -test

/bio/linuxbrew/Cellar/genometools/1.5.3/bin/gt
-test

/bio/linuxbrew/Cellar/genometools/1.5.3/bin/gt: error: could not find gtdata/ directory
Error: genometools: failed
Failed executing: /bio/linuxbrew/Cellar/genometools/1.5.3/bin/gt -test
```

**Comment by tdsmith** [comment]
Don't suppose this is resolved by #2183?

**Comment by tseemann** [comment]
CC: @sjackman 

I reinstalled latest 1.5.5 and still have the problems:

```
$ gt
gt: error: could not find gtdata/ directory
```


```
$ brew test genometools

Testing homebrew/science/genometools
==> /bio/linuxbrew/Cellar/genometools/1.5.5/bin/gt -test

/bio/linuxbrew/Cellar/genometools/1.5.5/bin/gt
-test

/bio/linuxbrew/Cellar/genometools/1.5.5/bin/gt: error: could not find gtdata/ directory
Error: homebrew/science/genometools: failed
Failed executing: /bio/linuxbrew/Cellar/genometools/1.5.5/bin/gt -test
/bio/linuxbrew/Library/Homebrew/formula.rb:888:in `block in system'
/bio/linuxbrew/Library/Homebrew/formula.rb:845:in `open'
/bio/linuxbrew/Library/Homebrew/formula.rb:845:in `system'
/bio/linuxbrew/Library/Taps/homebrew/homebrew-science/genometools.rb:44:in `block in <class:Genometools>'
/bio/linuxbrew/Library/Homebrew/formula.rb:788:in `block in run_test'
/bio/linuxbrew/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/bio/linuxbrew/Library/Homebrew/formula.rb:784:in `run_test'
/bio/linuxbrew/Library/Homebrew/test.rb:28:in `block in <main>'
/bio/linuxbrew/Cellar/ruby/2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
/bio/linuxbrew/Cellar/ruby/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
/bio/linuxbrew/Cellar/ruby/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
/bio/linuxbrew/Cellar/ruby/2.2.2/lib/ruby/2.2.0/timeout.rb:34:in `catch'
/bio/linuxbrew/Cellar/ruby/2.2.2/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
/bio/linuxbrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by tseemann** [comment]
Looks like someone tried (but failed?) to fix this in #2278

**Comment by sjackman** [comment]
How odd. It works when `HOMEBREW_PREFIX` is `/usr/local`, but does not when Homebrew is installed somewhere else (I can confirm this).

**Comment by sjackman** [comment]
Seems like the upstream bug is https://github.com/genometools/genometools/pull/569.

**Comment by yesimon** [comment]
Btw, the approach in #2278 is the right one, IMO, and is not an upstream problem, but rather a problem with the standard homebrew installation process.

The `/gtdata` is a special directory that needs to be copied to a special place. By default, since it is make installed to `bin/gtdata`, homebrew ignores it, that's why there's an extra `install` command in the formula to copy it to the Cellar. Normally this location is fine because genometools hardcoded searches `/usr/local/share/genometools` (https://github.com/genometools/genometools/blob/d41096076c129acb1407be0c38e5c2737fc0c0b4/src/core/gtdatapath.c#L35), which works if the prefix is `/usr/local`, but not otherwise. 

Since we already copy `/gtdata` to the Cellar, I added an extra symlink at the prefix for genometools search procedure to find it, which only works after genometools/genometools#569. So please take a look at #2278. :)

**Comment by sjackman** [comment]
#2278 failed @BrewTestBot, but the log has since been deleted. I've requested a rebuild.

**Comment by sjackman** [comment]
Installing data to `$prefix/bin` is an upstream bug. Data should be installed in `$prefix/share/$package`. I've opened an issue upstream. https://github.com/genometools/genometools/issues/618

**Comment by tseemann** [comment]
Is this solved now? https://github.com/Homebrew/homebrew-science/pull/2278

**Comment by sjackman** [comment]
#2278 does solve this issue.

**Comment by tseemann** [comment]
Successful Linux build! Thank you!

**Comment by sjackman** [comment]
No worries.
