### ISSUE TITLE
opencv fail to build with ffmpeg or vtk

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-science#3371]
When I try to install opencv `--with-ffmpeg` I got this error

```
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make
Last 15 lines from /Users/hanxue/Library/Logs/Homebrew/opencv/02.make:
                        AV_PIX_FMT_YUV422P
/usr/local/include/libavutil/pixfmt.h:67:5: note: 'AV_PIX_FMT_YUV422P' declared here
    AV_PIX_FMT_YUV422P,   ///< planar YUV 4:2:2, 16bpp, (1 Cr & Cb sample per 2x1 Y samples)
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [modules/highgui/CMakeFiles/opencv_highgui.dir/src/cap_ffmpeg.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 15%] Linking CXX shared library ../../lib/libopencv_video.dylib
cd /tmp/opencv20160226-98660-1n00lch/opencv-2.4.12/macbuild/modules/video && /usr/local/Cellar/cmake/3.4.3/bin/cmake -E cmake_link_script CMakeFiles/opencv_video.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++  -stdlib=libc++   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-array-bounds -Wno-aggressive-loop-optimizations -fdiagnostics-show-option -Wno-long-long -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -DNDEBUG  -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 2.4.0 -current_version 2.4.12 -o ../../lib/libopencv_video.2.4.12.dylib -install_name /tmp/opencv20160226-98660-1n00lch/opencv-2.4.12/macbuild/lib/libopencv_video.2.4.dylib CMakeFiles/opencv_video.dir/src/bgfg_gaussmix.cpp.o CMakeFiles/opencv_video.dir/src/bgfg_gaussmix2.cpp.o CMakeFiles/opencv_video.dir/src/bgfg_gmg.cpp.o CMakeFiles/opencv_video.dir/src/camshift.cpp.o CMakeFiles/opencv_video.dir/src/kalman.cpp.o CMakeFiles/opencv_video.dir/src/lkpyramid.cpp.o CMakeFiles/opencv_video.dir/src/motempl.cpp.o CMakeFiles/opencv_video.dir/src/optflowgf.cpp.o CMakeFiles/opencv_video.dir/src/simpleflow.cpp.o CMakeFiles/opencv_video.dir/src/tvl1flow.cpp.o CMakeFiles/opencv_video.dir/src/video_init.cpp.o ../../lib/libopencv_imgproc.2.4.12.dylib /usr/local/cuda/lib/libcudart.dylib /usr/local/cuda/lib/libnppc.dylib /usr/local/cuda/lib/libnppi.dylib /usr/local/cuda/lib/libnpps.dylib /usr/local/cuda/lib/libcufft.dylib ../../lib/libopencv_core.2.4.12.dylib /usr/local/cuda/lib/libcudart.dylib /usr/local/cuda/lib/libnppc.dylib /usr/local/cuda/lib/libnppi.dylib /usr/local/cuda/lib/libnpps.dylib -Wl,-rpath,/usr/local/cuda/lib 
cd /tmp/opencv20160226-98660-1n00lch/opencv-2.4.12/macbuild/modules/video && /usr/local/Cellar/cmake/3.4.3/bin/cmake -E cmake_symlink_library ../../lib/libopencv_video.2.4.12.dylib ../../lib/libopencv_video.2.4.dylib ../../lib/libopencv_video.dylib
```

Using `--with-vtk`, I got this

```
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
Last 15 lines from /Users/hanxue/Library/Logs/Homebrew/opencv/01.cmake:
-- Found apache ant 1.9.6: /usr/local/bin/ant
-- Found JNI: /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/jre/lib/libjawt.dylib  
CMake Error at /usr/local/Cellar/vtk/7.0.0/lib/cmake/vtk-7.0/vtkModuleAPI.cmake:120 (message):
  Requested modules not available:

    vtkRenderingOpenGL
Call Stack (most recent call first):
  /usr/local/lib/cmake/vtk-7.0/VTKConfig.cmake:88 (vtk_module_config)
  cmake/OpenCVDetectVTK.cmake:6 (find_package)
  CMakeLists.txt:532 (include)
```

This is my system
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: ecba11c8cd7d639c6bfa013ded07338b2b907d03
Last commit: 35 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 10.10.5-x86_64
Xcode: 6.4
CLT: 7.2.0.0.1.1447826929
GCC-4.2: build 5666
Clang: 6.1 build 602
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.2.1/bin/ruby
Java: 1.8.0_72, 1.7.0_40, 1.6.0_65-b14-466.1, 1.6.0_51-b11-457
```

**Comment by dpo** [comment]
Both `ffmpeg` and `vtk` were updated in the past few days. Did you update them?

**Comment by cyburgee** [comment]
i'm experiencing the same issue. using the latest homebrew version of ffmpeg (3.0).

**Comment by dpo** [comment]
It looks like they fixed at least the `ffmpeg` issues in HEAD for OpenCV3, but not for OpenCV2. This should be reported upstream.

**Comment by dpo** [comment]
Could you try #3380 for `ffmpeg`? See also https://github.com/Itseez/opencv/issues/6179.

**Comment by hyuce** [comment]
I updated ffmpeg and vtk in today. I am using this options with brew ;

`brew -v install --with-contrib --with-cuda --with-ffmpeg --with-gphoto2 --with-gstreamer --with-java --with-libdc1394 --with-opengl --with-openni2 --with-python3 --with-qt5 --with-tbb --with-vtk --HEAD opencv3`

When I compile, It shows this output.

`cd /tmp/opencv320160227-13282-4fw5vk/macbuild/modules/cudaarithm/CMakeFiles/cuda_compile.dir/src/cuda && /usr/local/Cellar/cmake/3.4.3/bin/cmake -D verbose:BOOL=1 -D build_configuration:STRING=Release -D generated_file:STRING=/tmp/opencv320160227-13282-4fw5vk/macbuild/modules/cudaarithm/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_add_weighted.cu.o -D generated_cubin_file:STRING=/tmp/opencv320160227-13282-4fw5vk/macbuild/modules/cudaarithm/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_add_weighted.cu.o.cubin.txt -P /tmp/opencv320160227-13282-4fw5vk/macbuild/modules/cudaarithm/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_add_weighted.cu.o.cmake
4 errors generated.
make[2]: *** [modules/viz/CMakeFiles/opencv_viz.dir/src/vtk/vtkCocoaInteractorFix.mm.o] Error 1
make[1]: *** [modules/viz/CMakeFiles/opencv_viz.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/tmp/opencv320160227-13282-4fw5vk/modules/core/include/opencv2/core/mat.inl.hpp(681): warning: integer conversion resulted in a change of sign`

Is this the same problem ?

**Comment by dpo** [comment]
I'm not sure. Bear in mind that we can't support `HEAD` builds. Please give #3380 a go.

**Comment by dpo** [comment]
See https://github.com/Itseez/opencv/issues/6180 regarding the build error related to VTK.

**Comment by hyuce** [comment]
VTK has been patched https://github.com/Kitware/VTK/commit/5f229e2e60a2c1427439ecb006bfc1ae47b4ef1d

**Comment by alokrajiv** [comment]
still facing error with cv2 build with ffmpeg

**Comment by Yetocome** [comment]
I have the same problem with ffmpeg, is there any patch?

**Comment by elmorg** [comment]
Also having this problem with ffmpeg: 

brew install opencv --with-ffmpeg
==> Installing opencv from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/Itseez/opencv/archive/2.4.12.tar.gz
Already downloaded: /Library/Caches/Homebrew/opencv-2.4.12.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make
Last 15 lines from /Users/xyz/Library/Logs/Homebrew/opencv/02.make:
/usr/local/include/libavutil/pixfmt.h:67:5: note: 'AV_PIX_FMT_YUV422P' declared here
    AV_PIX_FMT_YUV422P,   ///< planar YUV 4:2:2, 16bpp, (1 Cr & Cb sample per 2x1 Y samples)

**Comment by alokrajiv** [comment]
run `brew install` with flag `--HEAD` for now because the patch isn't in the release yet.

**Comment by ilovezfs** [comment]
Please re-test this with opencv 2.4.13, which I've just merged.

**Comment by heinemml** [comment]
Testing on OS X 10.11.5:
`brew install opencv --with-ffmpeg` builds without error.

`brew install opencv --with-vtk` fails with the following error:
```
/tmp/opencv-20160613-72735-1taadwg/opencv-2.4.13/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:284:81: error: no member named 'GetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
        vtkCocoaServerFix *server = reinterpret_cast<vtkCocoaServerFix*> (this->GetCocoaServer ());
                                                                          ~~~~  ^
/tmp/opencv-20160613-72735-1taadwg/opencv-2.4.13/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:285:20: error: no member named 'GetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
        if (!this->GetCocoaServer ())
             ~~~~  ^
/tmp/opencv-20160613-72735-1taadwg/opencv-2.4.13/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:288:19: error: no member named 'SetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
            this->SetCocoaServer (reinterpret_cast<void*> (server));
            ~~~~  ^
/tmp/opencv-20160613-72735-1taadwg/opencv-2.4.13/modules/viz/src/vtk/vtkCocoaInteractorFix.mm:300:81: error: no member named 'GetCocoaServer' in 'cv::viz::vtkCocoaRenderWindowInteractorFix'
        vtkCocoaServerFix *server = reinterpret_cast<vtkCocoaServerFix*> (this->GetCocoaServer ());
                                                                          ~~~~  ^
4 errors generated.
make[2]: *** [modules/viz/CMakeFiles/opencv_viz.dir/src/vtk/vtkCocoaInteractorFix.mm.o] Error 1
make[1]: *** [modules/viz/CMakeFiles/opencv_viz.dir/all] Error 2
```

To me that looks like a different problem than before. Should I open a new ticket? If this is could be confirmed on Yosemite we could close this ticket.

**Comment by ilovezfs** [comment]
This is making my head hurt. Does upstream even test this or are we doing something grievously wrong in the build?

**Comment by heinemml** [comment]
Okay, this really is messy. Essentially there are 2 commits on this issue upstream.

The CMake error (the one which was mentioned initially) was fixed in this commit for master
https://github.com/Itseez/opencv/commit/64a57f7c387f201094076120bfecf59719a95aea and this was also ported back to the 2.4 branch in this commit: https://github.com/Itseez/opencv/commit/d2e451e8774c67ec2d509651a45088883c0f4a99

The patch was applied after the 3.1 release, so the opencv3 package still has this problem. 2.4.13 was released after the patch so this problem doesn't occure anymore on the opencv package but a new bug turned up.

Bug number 2 is what I mentioned in the last post. It is already fixed in master (https://github.com/Itseez/opencv/commit/372890f1d7e4d6fbfbeda4c1f163c54e0c586eba) but wasn't ported back to 2.4. So it's fixed in HEAD, not fixed in 3.1 and 2.4.13

I will submit two pull requests pulling in the upstream patches. 
I suggested at https://github.com/Itseez/opencv/issues/6315 to port this patch back to the 2.4. branch upstream.

**Comment by ilovezfs** [comment]
I suspect we are best off just waiting for the next releases.

**Comment by heinemml** [comment]
Okay, to sum this up.

`--with-ffmpeg` should be working in the current state
`--with-vtk` is currently broken on opencv release and HEAD, on opencv3 release. opencv3 HEAD is working because it is fixed upstream. It should be working with vtk 6.x as the fixes are all related to vtk7. But you can't get vtk 6.x via homebrew.

Maybe we should close this issue and open a new one solely for the vtk bug to make this easier to find?

**Comment by dpo** [comment]
I'll close this now that #4336 was merged. Please open a new issue if problems remain with vtk.
