### ISSUE TITLE
vtk crashes when brewed python is installed

### ISSUE THREAD

**Issue by lantiga** [Homebrew/homebrew-science#3401]
### Indicate troubleshooting steps taken
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [n/a] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports / build errors:

After PR #3313 (see also discussion there), which leads vtk to link to system python when it is available, makes it impossible to have vtk coexist with brewed python without segfaulting. This is true both even if one forces building from source.

Scenario 1 (everything works with system python and no brewed python):
- start with no brew python and no brew vtk
- `which python` => `/usr/bin/python`
- `brew install vtk --with-python`
- `mkdir -p /Users/lantiga/Library/Python/2.7/lib/python/site-packages`
  `echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/lantiga/Library/Python/2.7/lib/python/site-packages/homebrew.pth`
- `python -c "import vtk"`
  => Ok

Scenario 2 (brew gets the bottled version, which links against system python, even when brewed python is installed, leading to a segfault):
- start with no brew python and no vtk
- `brew install python`
- `which python` => `/usr/local/bin/python`
- `brew install vtk --with-python`
- `python -c "import vtk"` => `Fatal Python error: PyThreadState_Get: no current thread. Abort trap: 6`

Scenario 3 (building vtk from source doesn't solve the problem, as cmake picks up system python even when brewed python is available and comes first in PATH):
- start with no brew python and no vtk
- `brew install python`
- `which python` => `/usr/local/bin/python`
- `brew install vtk --with-python --build-from-source`
- `python -c "import vtk"` => `Fatal Python error: PyThreadState_Get: no current thread. Abort trap: 6`

As an aside: - `/usr/bin/python -c "import vtk"` => Ok

To confirm, in Scenario 3:
`otool -L /usr/local/lib/python2.7/site-packages/vtk/vtkCommonCorePython.so`
gives

```
/usr/local/lib/python2.7/site-packages/vtk/vtkCommonCorePython.so:
    /usr/local/Cellar/vtk/7.0.0/lib/libvtkCommonCorePython27D-7.0.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/Cellar/vtk/7.0.0/lib/libvtkWrappingPython27Core-7.0.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/Cellar/vtk/7.0.0/lib/libvtkCommonCore-7.0.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
    /usr/local/Cellar/vtk/7.0.0/lib/libvtksys-7.0.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Another nuisance: anyone who got vtk 6.3 through brew --with-python in the past also got brewed python, which means that they now will see python crashing when they upgrade.

**Comment by lantiga** [comment]
@dpo sorry to bug you (I'm taking the conversation from #3313 here), do you have a timeframe for this? Let me know how I can help. Thanks

**Comment by dpo** [comment]
@lantiga Sorry for the delay. It's very busy for me at this time. I do want this resolved though. I'll cc @tdsmith who might have ideas or suggest potential problems.

**Comment by lantiga** [comment]
@dpo thank you for the feedback

**Comment by tdsmith** [comment]
http://www.vtk.org/Bug/view.php?id=16068

**Comment by gutia** [comment]
Same issue with both brewed python and vtk. In my case brewed vtk was linking against system python. So adding this to the path worked for me: 
`export LD_LIBRARY_PATH=/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib:$LD_LIBRARY_PATH`

**Comment by stefanoborini** [comment]
@gutia I am surprised it did, but I might be wrong. The problem are

1. Frameworks always take precedence over naked shared libraries, meaning that even if libpython27.dylib is in your library path, it won't be used as long as there is a framework for it
2. The LD_LIBRARY_PATH envvar is not used on OSX. The same variable is called DYLD_LIBRARY_PATH, but again, see 1.
3. The system framework path is hardcoded, so it will always be resolved to the system framework. You need to `install_name_tool -change` it to the brew python framework to get the correct resolution.

**Comment by iMichka** [comment]
Just a comment for @tdsmith. I also had a look at VTK cmake files and tried to hack something together (as I patched ITK lately for the same problem with success)

The thing with VTK is that the library linking commands are cluttered throughout multiple files, and it would probably need some bigger rewriting. As I do not know the VTK setup very well, I also abandoned after 1-2 hours of hacking. So somebody has to sit down for a few hours more to tackle the problem.

**Comment by desert0616** [comment]
Hi everyone, is this issues fixed already?
At the same time, is there any way to brew a older version to skirt this issue?

**Comment by gutia** [comment]
@stefanoborini Thank you for the reply! Yes, after I came back to it, I realized that didn't resolve the issue. :( I can't recover the steps that I did. I'm still not sure what is the correct resolution. Currently, I am just switched to using system python, but can't do this for a while as I also need ITK or SimpleITK.

**Comment by stefanoborini** [comment]
@gutia if the system python is the same version, you can just use `install_name_tool` to change the dependency.

**Comment by desert0616** [comment]
@lantiga Hi, I was wondering that there is any temporary approach to handling this problem. Or I have to use default python for now. Thanks.

**Comment by dchammond** [comment]
Hi, what is the current status here?  If I do not specify any python flags, will vtk install?

**Comment by gnamor** [comment]
For me the VTK installs, but still fails when I do "import vtk" in the brew installed python. It works for the system installed python.
Any solution on the horizon?
Thank you!

**Comment by iMichka** [comment]
For the record, I started to work on a patch. Please do not use this in production :)

We used the same strategy in ITK and SimpleITK to fix this problem.
I just started a branch of master to play around. Its the beginning, but it already works with brewed python: https://github.com/iMichka/VTK/commit/a42023af0155f29307f9ee9f3afdce2fcd9e9ed9

I will need a few days to finish to test and clean this up, and I'll submit the patch upstream.

**Comment by Chrismarsh** [comment]
iMichka, this is good news. Thanks very much for your effort. Currently this bug is blocking me, so I look forward to your full patch.

Is there a simple way to testing this out? Despite using Homebrew, I'm not entirely familiar how it's backend scripts work for pulling other patches in.

**Comment by iMichka** [comment]
You can git clone the VTK project from my fork, checkout my branch (vtkNoPythonLink), modify your local vtk formula by adding ```head "/Users/myname/VTK", :using => :git, :branch => "vtkNoPythonLink"```, and use brew install vtk --HEAD. (not tested, I am directly building VTK manually for the moment). Also, you may need to set VTK_ENABLE_VTKPYTHON=OFF.

I'll continue to work on this tomorrow. Testing is always welcome.

**Comment by Chrismarsh** [comment]
Strangely, I don't have a local VTK formula in /usr/local/Library/Formula, so I copied one from the hombrew science repo.

Modified it as per your instructions.

Checkout and switched to the vtkNoPythonLink branch.
Then ran 
>export VTK_ENABLE_VTKPYTHON=OFF; brew install vtk --HEAD --with-python --build-from-source

I see it cloning my copy of your forked repo, so it seems to be doing 'the right thing'.
```
==> Cloning /Users/chris/Desktop/VTK
Updating /Library/Caches/Homebrew/vtk--git
==> Checking out branch vtkNoPythonLink
```
During compilation, itI dies here:

```
 [ 10%] Python Wrapping - generating vtkConditionVariablePython.cxx
1745 cd /tmp/vtk-20160518-13113-i90zos/build/Wrapping/Python && ../../bin/vtkWrapPython-7.1 @/tmp/vtk-20160518-13113-i90zos/build/Wrapping/Python/vtkCommonCorePython.Release.args -o /tmp/vtk-20160518-13113-i90zos/build/Wrapping/Python/v     tkConditionVariablePython.cxx /tmp/vtk-20160518-13113-i90zos/Common/Core/vtkConditionVariable.h
1746 Undefined symbols for architecture x86_64:
1747   "_PyEval_InitThreads", referenced from:
1748       _main in vtkPythonAppInit.cxx.o
1749   "_PyList_Insert", referenced from:
1750       vtkPythonAppInitPrependPythonPath(char const*) in vtkPythonAppInit.cxx.o
1751   "_PyString_AsString", referenced from:
1752       _main in vtkPythonAppInit.cxx.o
1753   "_PyString_FromString", referenced from:
1754       vtkPythonAppInitPrependPythonPath(char const*) in vtkPythonAppInit.cxx.o
1755   "_PySys_GetObject", referenced from:
1756       _main in vtkPythonAppInit.cxx.o
1757       vtkPythonAppInitPrependPythonPath(char const*) in vtkPythonAppInit.cxx.o
1758   "_Py_Initialize", referenced from:
1759       _main in vtkPythonAppInit.cxx.o
1760   "_Py_Main", referenced from:
1761       _main in vtkPythonAppInit.cxx.o
1762   "_Py_SetProgramName", referenced from:
1763       _main in vtkPythonAppInit.cxx.o
1764 ld: symbol(s) not found for architecture x86_64
1765 clang: error: linker command failed with exit code 1 (use -v to see invocation)
1766 make[2]: *** [bin/vtkpython] Error 1
1767 make[1]: *** [Wrapping/Python/CMakeFiles/vtkpython.dir/all] Error 2
1768 make[1]: *** Waiting for unfinished jobs....
```
1769 [ 10%] Building CXX object Common/Transforms/CMakeF

**Comment by iMichka** [comment]
@Chrismarsh the vtk formula is in homebrew-science, under: ```/usr/local/Library/Taps/homebrew/homebrew-science```.

I updated my patch, which works now with ```VTK_ENABLE_VTKPYTHON=ON```
https://github.com/iMichka/VTK/commit/8a6eafa5a53c7f9c0f7b8492c6aa840d020ff23d

@dpo @tdsmith I have a question for you. VTK is building it's own Python interpreter, called ```vtkpython```, and which will be installed under ```/usr/local/bin/vtkpython```. This interpreter is optional and does not necessarily needs to be used, but some people may need it for convenience.

I tried to remove the linking to libpython.dylib from vtkPython, and also used the ```-undefined dynamic_lookup```flag on that target. It builds, but running it fails:

> $ /usr/local/bin/vtkpython
 dyld: Symbol not found: _PyBaseObject_Type
  Referenced from: /usr/local/lib/libvtkWrappingPython27Core-7.1.1.dylib
  Expected in: flat namespace
 in /usr/local/lib/libvtkWrappingPython27Core-7.1.1.dylib
[1]    37428 trace trap  /usr/local/bin/vtkpythonut running this python interpreter fails with:

Linking specifically against the dylib makes it work (see https://github.com/iMichka/VTK/commit/8a6eafa5a53c7f9c0f7b8492c6aa840d020ff23d#diff-8fff9c1ae96e43d16a5d9675a19d3f2bR246). Do you know if the dynamic loading of symbols works in this case ?

On my TO DO list:
- test with python3
- test all the modules: SixPython, MPI4Py, AutobahnPython, Twisted, ZopeInterface, Web
- test the build on Linux

Once all this is done we can the submit the patch. A lot of work :) If somebody is motivated and knows about the submodules, help would be appreciated.

**Comment by Chrismarsh** [comment]
@iMichka Ah yes, there it is. Thanks.

After updating to your latest patch, still isn't compiling for me. Still undefined references to _PyEval_InitThreads

**Comment by iMichka** [comment]
I submitted the patch upstream: https://gitlab.kitware.com/vtk/vtk/merge_requests/1511
It is still a work in progress. The discussion can continue there and come back here once it is merged.

For your build problem, let's try to get that sorted out here:
- Make sure my branch is up to date: I ammended the commit I made
- Do you have brewed python installed ?
- Are you building with ```brew install --HEAD  --with-python```(no fancy options ?)
- VTK_ENABLE_VTKPYTHON can stay on ON, no need to modify it with my latest patch
- Could you please use ```brew gist-logs vtk``` to provide the full build log ?

**Comment by Chrismarsh** [comment]
Yes to all your questions.

However, your latest patch fixes the compile. I will test further tomorrow.

**Comment by Chrismarsh** [comment]
For my workflow of reading vtu files I generate elsewhere, as well as the vtk_to_numpy features, it all seems to work without any issues.

**Comment by puiseux** [comment]
Is there some correction for this bug ?
i uninstall, reinstall python
`brew uninstall python && brew install python`
then vtk
`brew uninstall vtk`
`brew install --with-python --with-qt vtk`
it try this : `python -c "import vtk"`

> Fatal Python error: PyThreadState_Get: no current thread
> Abort trap: 6

and this :
`/usr/bin/python -c "import vtk"` => OK

is it possible to install old vtk-5 with python ? It was working perfectly for me, but now I can't code anymore...  Anyway, the sun shines, mountains are not far, so...

**Comment by iMichka** [comment]
I removed VTK5 lately, you can see the reasons in the commit message: https://github.com/Homebrew/homebrew-science/commit/7d8296ed144b6fbaf351a2178b4f003ba8b2557b
If you really want it back, the best way is to setup your own tap, and maintain the vtk5 formula yourself (or discuss with the homebrew maintainers a way to bring it back, but this is not my decision to take).

For the problem with python, you should be able to use system python.
As stated above, I submitted a patch upstream to fix this, but it takes more time than planned. Hopefully I will be able to work on this during the next days.

**Comment by dpo** [comment]
@lantiga Could you give #3811 a try and let us know if it works for you?

**Comment by lantiga** [comment]
Works for me! Thanks so much to all who contributed so far.

**Comment by puiseux** [comment]
Sorry to be so late, i was on holidays.
I don’t really understand what you want me to try …
I’ve tried 
[Mar jul 26][04:52 ]@[bin] $ brew audit --strict --online vtk
==> Installing or updating 'rubocop' gem
Fetching: rainbow-2.1.0.gem (100%)
Successfully installed rainbow-2.1.0
Fetching: ast-2.3.0.gem (100%)
Successfully installed ast-2.3.0
Fetching: parser-2.3.1.2.gem (100%)
Successfully installed parser-2.3.1.2
Fetching: powerpack-0.1.1.gem (100%)
Successfully installed powerpack-0.1.1
Fetching: ruby-progressbar-1.8.1.gem (100%)
Successfully installed ruby-progressbar-1.8.1
Fetching: unicode-display_width-1.1.0.gem (100%)
Successfully installed unicode-display_width-1.1.0
Fetching: rubocop-0.41.2.gem (100%)
Successfully installed rubocop-0.41.2
7 gems installed
homebrew/science/vtk:
  * Use pkgshare instead of (share+"vtk")
  * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkChartsCorePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkCommonColorPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkCommonComputationalGeometryPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkCommonCorePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkCommonDataModelPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkCommonExecutionModelPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkCommonMathPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkCommonMiscPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkCommonSystemPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkCommonTransformsPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkDomainsChemistryOpenGL2Python.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkDomainsChemistryPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersAMRPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersCorePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersExtractionPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersFlowPathsPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersGeneralPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersGenericPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersGeometryPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersHybridPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersHyperTreePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersImagingPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersModelingPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersParallelImagingPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersParallelPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersProgrammablePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersPythonPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersSelectionPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersSMPPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersSourcesPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersStatisticsPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersTexturePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkFiltersVerdictPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkGeovisCorePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkImagingColorPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkImagingCorePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkImagingFourierPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkImagingGeneralPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkImagingHybridPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkImagingMathPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkImagingMorphologicalPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkImagingSourcesPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkImagingStatisticsPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkImagingStencilPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkInfovisBoostGraphAlgorithmsPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkInfovisCorePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkInfovisLayoutPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkInteractionImagePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkInteractionStylePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkInteractionWidgetsPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOAMRPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOCorePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOEnSightPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOExodusPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOExportPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOGeometryPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOImagePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOImportPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOInfovisPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOLegacyPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOLSDynaPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOMINCPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOMoviePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIONetCDFPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOParallelPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOParallelXMLPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOPLYPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOSQLPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOVideoPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOXMLParserPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkIOXMLPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkParallelCorePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingAnnotationPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingContext2DPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingContextOpenGL2Python.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingCorePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingFreeTypePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingImagePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingLabelPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingLODPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingOpenGL2Python.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingQtPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingVolumeOpenGL2Python.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkRenderingVolumePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkViewsContext2DPython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkViewsCorePython.so
      /usr/local/Cellar/vtk/7.0.0_1/lib/python2.7/site-packages/vtk/vtkViewsInfovisPython.so
Error: 2 problems in 1 formula

Well, now i cannot figure out what i have to do…

**Comment by iMichka** [comment]
It's okay I did all the testing myself. A patch was merged to VTK; then reverted because it introduced 2 regressions. I fixed the first one yesterday. You'll have to wait until my patch goes in.

**Comment by fbender** [comment]
Seems like this is continued in [!1713](https://gitlab.kitware.com/vtk/vtk/merge_requests/1713) – does #3811 add the patch to fix the issue before upstream is able to merge?

**Comment by iMichka** [comment]
#3811 does not contain the fixes for the 2 issues we had with the first patch, and should not be merged.

https://gitlab.kitware.com/vtk/vtk/merge_requests/1713 has the matplotlib issue fixed. The second one; the integration with the KITS flag, is still not done. As stated in https://gitlab.kitware.com/vtk/vtk/merge_requests/1713, I am on holidays until next week, so I won't be working on this anyway.

What needs to be done:
- https://gitlab.kitware.com/vtk/vtk/merge_requests/1713 needs to be merged upstream, but for this the KITS problem needs to be solved
- The patch needs to be back ported to #3811

If it is urgent anybody can continue to work on this, but you'll probably want to wait until next week :)

**Comment by fbender** [comment]
@iMichka thanks for the quick reply! I'm currently looking for a quick fix to be able to continue with my thesis. I assume I can ignore the KITS issue for my setup, and just manually redo your formula changes in #3811 with the updated patch. Or I just switch to the system python binary for the moment …

**Comment by iMichka** [comment]
Yes the easiest thing is to use my patch from #3811 manually, and keep an eye on this thread until the problem is solved.

**Comment by valbertoenoc** [comment]
TL;DR: brew vtk works fine with brew python3. 

@iMichka , I have been moving around this issue for a while now, and I finally, arrived at a solutions that works for me. 
I reinstalled vtk with python3 support and everything worked fine. (if you have already installed you might have to reinstall it with the --with-python3 and --without-python flags, since vtk doesn't currently support both wrappers at once).
Beforehand, I was trying to make it work with the system python, but I always would run into problems when trying to install a new package, (It would help if someone pointed me a way to change system python site package to home-brew site package, everything i did didnt work, and for the record I ran into that trying to make system python find modules wxpython and pyqt4 from home-brew installations). So I had to change all my environment to python3, but I've been wanting to that for a while now anyways.

I know that maybe for some people changing to python3 is an issue, but considering that is not that easy to get your hands on an older vtk versions (assuming it would work) and this issue has been particularly difficult to solve, it might be a could time to consider porting your environment and necessary packages to python3. 

I hope this helps in some way.

**Comment by iMichka** [comment]
@valbertoenoc The problem would still be there with python 3. If you try to import the vtk you built with a python 3 coming from anaconda, macports, or from the python.org website, it would still crash.

The problem is well known, the patch adresses that problem. We know what needs to be fixed to make it work in a more general way. Thanks for the report though.

**Comment by jonchang** [comment]
Hi all, thanks for your patience with this issue. While we wait for upstream to provide a more permanent fix, if you are a current user of VTK + brewed Python, could you please test the patch in #4342?

Apply the patch then run

```
brew postinstall vtk
python -c "import vtk"
```

and see if it fixes the crashes?

**Comment by butala** [comment]
I was having the aforementioned issue. I applied the patch and am now able to use VTK with the homebrewed python2.

Thank you for the patch!

**Comment by puiseux** [comment]
Still crashes :
```
[Lun sep 26][05:05 ]@[TP2] $ brew postinstall vtk
[Lun sep 26][05:31 ]@[TP2] $ python -c "import vtk"
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```
maybe this can help :

Process:               Python [5780]
Path:                  /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.12 (2.7.12)
Code Type:             X86-64 (Native)
Parent Process:        bash [872]
Responsible:           Terminal [800]
User ID:               501

Date/Time:             2016-09-26 05:31:54.872 +0200
OS Version:            Mac OS X 10.11.6 (15G1004)
Report Version:        11
Anonymous UUID:        1CFE7E76-D4C9-6335-E847-5FCAF6C8D4A0


Time Awake Since Boot: 34000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff969f3f06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff961034ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff92ce86df abort + 129
3   org.python.python             	0x000000010aee6ce2 Py_FatalError + 49
4   org.python.python             	0x000000010aee61f0 PyThreadState_Get + 28
5   org.python.python             	0x000000010aee303a Py_InitModule4_64 + 62
6   libvtkCommonCorePython27D-7.0.1.dylib	0x000000010a9ba9a2 real_initvtkCommonCorePython + 36
7   org.python.python             	0x000000010a391758 _PyImport_LoadDynamicModule + 140
8   org.python.python             	0x000000010a390454 import_submodule + 267
9   org.python.python             	0x000000010a390028 load_next + 280
10  org.python.python             	0x000000010a38f208 PyImport_ImportModuleLevel + 1129
11  org.python.python             	0x000000010a370fbd builtin___import__ + 135
12  org.python.python             	0x000000010a2fce95 PyObject_Call + 99
13  org.python.python             	0x000000010a37fb2b PyEval_CallObjectWithKeywords + 165
14  org.python.python             	0x000000010a37ace3 PyEval_EvalFrameEx + 20788
15  org.python.python             	0x000000010a3759bf PyEval_EvalCodeEx + 1618
16  org.python.python             	0x000000010a375367 PyEval_EvalCode + 48
17  org.python.python             	0x000000010a38dced PyImport_ExecCodeModuleEx + 241
18  org.python.python             	0x000000010a3909ef load_source_module + 1095
19  org.python.python             	0x000000010a390454 import_submodule + 267
20  org.python.python             	0x000000010a390028 load_next + 280
21  org.python.python             	0x000000010a38f208 PyImport_ImportModuleLevel + 1129
22  org.python.python             	0x000000010a370fbd builtin___import__ + 135
23  org.python.python             	0x000000010a2fce95 PyObject_Call + 99
24  org.python.python             	0x000000010a37fb2b PyEval_CallObjectWithKeywords + 165
25  org.python.python             	0x000000010a37ace3 PyEval_EvalFrameEx + 20788
26  org.python.python             	0x000000010a3759bf PyEval_EvalCodeEx + 1618
27  org.python.python             	0x000000010a375367 PyEval_EvalCode + 48
28  org.python.python             	0x000000010a38dced PyImport_ExecCodeModuleEx + 241
29  org.python.python             	0x000000010a3909ef load_source_module + 1095
30  org.python.python             	0x000000010a390c77 load_package + 303
31  org.python.python             	0x000000010a390454 import_submodule + 267
32  org.python.python             	0x000000010a390028 load_next + 280
33  org.python.python             	0x000000010a38f208 PyImport_ImportModuleLevel + 1129
34  org.python.python             	0x000000010a370fbd builtin___import__ + 135
35  org.python.python             	0x000000010a2fce95 PyObject_Call + 99
36  org.python.python             	0x000000010a37fb2b PyEval_CallObjectWithKeywords + 165
37  org.python.python             	0x000000010a37ace3 PyEval_EvalFrameEx + 20788
38  org.python.python             	0x000000010a3759bf PyEval_EvalCodeEx + 1618
39  org.python.python             	0x000000010a375367 PyEval_EvalCode + 48
40  org.python.python             	0x000000010a398d0e run_mod + 53
41  org.python.python             	0x000000010a398b3c PyRun_InteractiveOneFlags + 377
42  org.python.python             	0x000000010a398630 PyRun_InteractiveLoopFlags + 192
43  org.python.python             	0x000000010a3984da PyRun_AnyFileExFlags + 60
44  org.python.python             	0x000000010a3aa26d Py_Main + 3101
45  libdyld.dylib                 	0x00007fff8ce9a5ad start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff559155a8  rdx: 0x0000000000000000
  rdi: 0x0000000000000a0b  rsi: 0x0000000000000006  rbp: 0x00007fff559155d0  rsp: 0x00007fff559155a8
   r8: 0x0000000000000040   r9: 0x00007fff745ad1e0  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x00007fb7d1839000  r13: 0x000000010aa43cd5  r14: 0x00007fff74c77000  r15: 0x000000010a4223a0
  rip: 0x00007fff969f3f06  rfl: 0x0000000000000206  cr2: 0x00007fff745ab008
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133


Binary Images:
       0x10a2e9000 -        0x10a2eafff +org.python.python (2.7.12 - 2.7.12) <4311642B-4C66-3712-BA32-7C82ABC84ED0> /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
       0x10a2f2000 -        0x10a3e7ff7 +org.python.python (2.7.12, [c] 2001-2016 Python Software Foundation. - 2.7.12) <9A53817F-2101-3965-9831-1DB81D851FBA> /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/Python
       0x10a817000 -        0x10a819fff +_locale.so (0) <6758A21E-3D2B-3620-952A-68EC384CC1AF> /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_locale.so
       0x10a85c000 -        0x10a85efff +readline.so (0) <EF0C9AA6-617C-35CF-B12C-FD60E3BF51F1> /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/readline.so
       0x10a864000 -        0x10a885ff7 +libreadline.6.dylib (0) <D0BFE0C1-DA5F-3D72-9D16-99235FE8D948> /usr/local/opt/readline/lib/libreadline.6.dylib
       0x10a89c000 -        0x10a89efff +vtkCommonCorePython.so (0) <3B62824C-94B1-3FB1-827C-D030F69C20F1> /usr/local/lib/python2.7/site-packages/vtk/vtkCommonCorePython.so
       0x10a8a1000 -        0x10aa4afff +libvtkCommonCorePython27D-7.0.1.dylib (0) <B68E5E59-605E-3E76-8187-7A7B8B58EA82> /usr/local/Cellar/vtk/7.0.0_2/lib/libvtkCommonCorePython27D-7.0.1.dylib
       0x10ab33000 -        0x10ab4dff3 +libvtkWrappingPython27Core-7.0.1.dylib (0) <E68AC9FD-CB77-33D6-9551-2CEF8E37C73E> /usr/local/Cellar/vtk/7.0.0_2/lib/libvtkWrappingPython27Core-7.0.1.dylib
       0x10ab60000 -        0x10ad4bfe7 +libvtkCommonCore-7.0.1.dylib (0) <6090EC64-6325-303A-9BCA-A7C611A65080> /usr/local/Cellar/vtk/7.0.0_2/lib/libvtkCommonCore-7.0.1.dylib
       0x10ae45000 -        0x10af36ff7  org.python.python (2.7.10 - 2.7.10) <83AFAAA7-BDFA-354D-8A7A-8F40A30ACB91> /System/Library/Frameworks/Python.framework/Versions/2.7/Python
       0x10af9d000 -        0x10afc8ffb +libvtksys-7.0.1.dylib (0) <A24DDEAD-1EC1-37B7-BD08-5D07B9CCDCD2> /usr/local/Cellar/vtk/7.0.0_2/lib/libvtksys-7.0.1.dylib
    0x7fff6f177000 -     0x7fff6f1aea47  dyld (360.22) <DC81CC9D-651A-3A45-8809-928282052BD3> /usr/lib/dyld
    0x7fff82d21000 -     0x7fff82d26ff7  libmacho.dylib (875.1) <318264FA-58F1-39D8-8285-1F6254EE410E> /usr/lib/system/libmacho.dylib
    0x7fff835e7000 -     0x7fff8362dff7  libauto.dylib (186) <999E610F-41FC-32A3-ADCA-5EC049B65DFB> /usr/lib/libauto.dylib
    0x7fff855c2000 -     0x7fff855c2ff7  liblaunch.dylib (765.50.8) <834ED605-5114-3641-AA4D-ECF31B801C50> /usr/lib/system/liblaunch.dylib
    0x7fff855fd000 -     0x7fff85614ff7  libsystem_asl.dylib (323.50.1) <41F8E11F-1BD0-3F1D-BA3A-AA1577ED98A9> /usr/lib/system/libsystem_asl.dylib
    0x7fff85c19000 -     0x7fff85f7bf3f  libobjc.A.dylib (680) <7489D2D6-1EFD-3414-B18D-2AECCCC90286> /usr/lib/libobjc.A.dylib
    0x7fff86541000 -     0x7fff8674efff  libicucore.A.dylib (551.51.4) <3899B146-3840-3D4A-8C4A-FE391D5D25C7> /usr/lib/libicucore.A.dylib
    0x7fff86a9e000 -     0x7fff86aa6ffb  libsystem_dnssd.dylib (625.60.4) <80189998-32B0-316C-B5C5-53857486713D> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff875a5000 -     0x7fff875d4ffb  libsystem_m.dylib (3105) <08E1A4B2-6448-3DFE-A58C-ACC7335BE7E4> /usr/lib/system/libsystem_m.dylib
    0x7fff875df000 -     0x7fff875fbff7  libsystem_malloc.dylib (67.40.1) <5748E8B2-F81C-34C6-8B13-456213127678> /usr/lib/system/libsystem_malloc.dylib
    0x7fff8761a000 -     0x7fff87622fef  libsystem_platform.dylib (74.40.2) <29A905EF-6777-3C33-82B0-6C3A88C4BA15> /usr/lib/system/libsystem_platform.dylib
    0x7fff87e42000 -     0x7fff87e49ff7  libcompiler_rt.dylib (62) <A13ECF69-F59F-38AE-8609-7B731450FBCD> /usr/lib/system/libcompiler_rt.dylib
    0x7fff880b9000 -     0x7fff880c1fff  libcopyfile.dylib (127) <A48637BC-F3F2-34F2-BB68-4C65FD012832> /usr/lib/system/libcopyfile.dylib
    0x7fff885c0000 -     0x7fff885c2fff  libsystem_coreservices.dylib (19.2) <1B3F5AFC-FFCD-3ECB-8B9A-5538366FB20D> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff888fc000 -     0x7fff8894fff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib
    0x7fff88990000 -     0x7fff88991ffb  libSystem.B.dylib (1226.10.1) <012548CD-614D-3AF0-B3B1-676F427D2CD6> /usr/lib/libSystem.B.dylib
    0x7fff8a0af000 -     0x7fff8a0b0fff  libsystem_blocks.dylib (65) <1244D9D5-F6AA-35BB-B307-86851C24B8E5> /usr/lib/system/libsystem_blocks.dylib
    0x7fff8a6a3000 -     0x7fff8a6a5ff7  libquarantine.dylib (80) <0F4169F0-0C84-3A25-B3AE-E47B3586D908> /usr/lib/system/libquarantine.dylib
    0x7fff8a73d000 -     0x7fff8a73dff7  libkeymgr.dylib (28) <8371CE54-5FDD-3CE9-B3DF-E98C761B6FE0> /usr/lib/system/libkeymgr.dylib
    0x7fff8ae92000 -     0x7fff8ae94ff7  libsystem_configuration.dylib (802.40.13) <3DEB7DF9-6804-37E1-BC83-0166882FF0FF> /usr/lib/system/libsystem_configuration.dylib
    0x7fff8ce97000 -     0x7fff8ce9affb  libdyld.dylib (360.22) <25D28225-99AE-3A04-B98C-ACFF47D6D9B0> /usr/lib/system/libdyld.dylib
    0x7fff8ea8c000 -     0x7fff8ea8ffff  libsystem_sandbox.dylib (460.60.2) <2A68B39C-B786-3A05-87A2-56E688469FB8> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff8ea90000 -     0x7fff8eac1ff7  libncurses.5.4.dylib (46) <D4C10699-3E8F-3F42-A695-7490EA4B6B32> /usr/lib/libncurses.5.4.dylib
    0x7fff8ef37000 -     0x7fff8ef4eff7  libsystem_coretls.dylib (83.40.5) <C90DAE38-4082-381C-A185-2A6A8B677628> /usr/lib/system/libsystem_coretls.dylib
    0x7fff8ef51000 -     0x7fff8ef7bff7  libc++abi.dylib (307.2) <922EFB36-0E9E-315B-8270-E81AC43472C0> /usr/lib/libc++abi.dylib
    0x7fff8f48a000 -     0x7fff8f48efff  libcache.dylib (75) <9548AAE9-2AB7-3525-9ECE-A2A7C4688447> /usr/lib/system/libcache.dylib
    0x7fff8f48f000 -     0x7fff8f4a0ff7  libz.1.dylib (61.20.1) <B3EBB42F-48E3-3287-9F0D-308E04D407AC> /usr/lib/libz.1.dylib
    0x7fff8f879000 -     0x7fff8f882ff3  libsystem_notify.dylib (150.40.1) <D48BDE34-0F7E-34CA-A0FF-C578E39987CC> /usr/lib/system/libsystem_notify.dylib
    0x7fff90426000 -     0x7fff9089cfff  com.apple.CoreFoundation (6.9 - 1258.1) <943A1383-DA6A-3DC0-ABCD-D9AEB3D0D34D> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff90985000 -     0x7fff90985ff7  libunc.dylib (29) <DDB1E947-C775-33B8-B461-63E5EB698F0E> /usr/lib/system/libunc.dylib
    0x7fff90b74000 -     0x7fff90b9dfff  libsystem_info.dylib (477.50.4) <FAA9226D-64DE-3769-A6D8-6CABA4B7FF4D> /usr/lib/system/libsystem_info.dylib
    0x7fff90dc0000 -     0x7fff90dc1fff  libsystem_secinit.dylib (20) <32B1A8C6-DC84-3F4F-B8CE-9A52B47C3E6B> /usr/lib/system/libsystem_secinit.dylib
    0x7fff90f61000 -     0x7fff90f8efff  libdispatch.dylib (501.40.12) <C7499857-61A5-3D7D-A5EA-65DCC8C3DF92> /usr/lib/system/libdispatch.dylib
    0x7fff91795000 -     0x7fff91796ffb  libremovefile.dylib (41) <552EF39E-14D7-363E-9059-4565AC2F894E> /usr/lib/system/libremovefile.dylib
    0x7fff92c8a000 -     0x7fff92d17fef  libsystem_c.dylib (1082.60.1) <28733D22-553E-3CBC-8D2C-EDCEB46E46AF> /usr/lib/system/libsystem_c.dylib
    0x7fff947c5000 -     0x7fff947cdfff  libsystem_networkextension.dylib (385.40.36) <66095DC7-6539-38F2-95EE-458F15F6D014> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff94832000 -     0x7fff9483dff7  libcommonCrypto.dylib (60075.50.1) <93732261-34B4-3914-B7A2-90A81A182DBA> /usr/lib/system/libcommonCrypto.dylib
    0x7fff95ada000 -     0x7fff95adbfff  libDiagnosticMessagesClient.dylib (100) <4243B6B4-21E9-355B-9C5A-95A216233B96> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff960fd000 -     0x7fff96106ff7  libsystem_pthread.dylib (138.10.4) <3DD1EF4C-1D1B-3ABF-8CC6-B3B1CEEE9559> /usr/lib/system/libsystem_pthread.dylib
    0x7fff961cf000 -     0x7fff961e0ff7  libsystem_trace.dylib (201.10.3) <E9311C03-9E61-3B13-AF3F-A64956FFF269> /usr/lib/system/libsystem_trace.dylib
    0x7fff9631d000 -     0x7fff96322ff3  libunwind.dylib (35.3) <F6EB48E5-4D12-359A-AB54-C937FBBE9043> /usr/lib/system/libunwind.dylib
    0x7fff96971000 -     0x7fff9699aff7  libxpc.dylib (765.50.8) <54D1328E-054E-3DAA-89E2-375722F9D18F> /usr/lib/system/libxpc.dylib
    0x7fff969dd000 -     0x7fff969fbff7  libsystem_kernel.dylib (3248.60.11) <A3F069EA-6A41-35CA-BDF8-187E0209B3E2> /usr/lib/system/libsystem_kernel.dylib
    0x7fff96cf1000 -     0x7fff96d68feb  libcorecrypto.dylib (335.50.1) <B5C05FD7-A540-345A-87BF-8E41848A3C17> /usr/lib/system/libcorecrypto.dylib
    0x7fff96ea2000 -     0x7fff96f08ff7  libsystem_network.dylib (583.50.1) <B52DAB73-92DC-3DA7-B9F4-B899D66445C1> /usr/lib/system/libsystem_network.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 7495
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=113.8M resident=0K(0%) swapped_out_or_unallocated=113.8M(100%)
Writable regions: Total=68.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=68.3M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                  2048K        2 
Kernel Alloc Once                    4K        2 
MALLOC                            56.4M       12 
MALLOC guard page                   16K        4 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                       1540K        5 
__DATA                            3892K       60 
__LINKEDIT                        93.6M       14 
__TEXT                            20.2M       57 
__UNICODE                          552K        2 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                            242.1M      153 

Model: MacBookPro11,3, BootROM MBP112.0138.B17, 4 processors, Intel Core i7, 2,8 GHz, 16 GB, SMC 2.19f12
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.6f1 17910, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
PCI Card: Apple 57761-B0, Ethernet Controller, Thunderbolt@192,0,0
PCI Card: pci11c1,5901, IEEE 1394 Open HCI, Thunderbolt@191,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@197,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@197,0,1
PCI Card: pci12d8,400f, USB Enhanced Host Controller, Thunderbolt@197,0,2
Serial ATA Device: APPLE SSD SM1024F, 1 TB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Display)
USB Device: Apple Thunderbolt Display
USB Device: Display Audio
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1
Thunderbolt Device: Thunderbolt Display, Apple Inc., 3, 26.2

**Comment by jonchang** [comment]
@puiseux, the patch isn't in Homebrew yet. So you'll have to apply it yourself. It doesn't look like it got applied in your case, as there should be a message when you run `brew postinstall vtk` that says something like `Patching VTK to use Homebrew's Python`

**Comment by butala** [comment]
I can confirm that the patch works. The general steps are:

1. Download patch: https://github.com/Homebrew/homebrew-science/pull/4342.patch
2. Apply patch: `patch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/vtk.rb 4342.patch`
3. Install: `homebrew install vtk`

**Comment by dmwelch** [comment]
I can confirm the patch.  FYI: My commands/paths were slightly different from @butala -
```
$ patch /usr/local/Library/Taps/homebrew/homebrew-science/vtk.rb 4342.patch 
$ brew install vtk
```

Then to verify:
```
$ python -c "import vtk"
```

**Comment by iMichka** [comment]
Hi. I would propose to close this bug. A workaround has been merged, and we can live with that for the moment. The real fix is coming with #3811, but we are still waiting for upstream to make a move. The discussion should continue in #3811.

**Comment by rambalachandran** [comment]
When I tried to download and apply the above patch, it throws me the following error
```
Hunk #1 FAILED at 4.
Hunk #2 succeeded at 189 with fuzz 1 (offset 38 lines).
Hunk #3 FAILED at 235.
Hunk #4 succeeded at 271 (offset 46 lines).
2 out of 4 hunks FAILED -- saving rejects to file /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/vtk.rb.rej
```

**Comment by iMichka** [comment]
You do not need to apply the patch. The current version does not need it.
You can switch between between brewed python and system python with:

> brew postinstall vtk

This is explained in the Caveats section of the formula installation (brew info vtk).

I am still in favour of closing this bug. The problem is solved with the current workaround. The  real fix is still waiting for an upstream merge (see #3811)

**Comment by rambalachandran** [comment]
Yes I can confirm that `import vtk` now works inside a python console

**Comment by rambalachandran** [comment]
Also do you know how to make it work with virtualenv python derived from Homebrew python?

**Comment by tdsmith** [comment]
Create your virtualenv with --system-site-packages or write a .pth file to your virtualenv's site-packages that references /usr/local/opt/vtk/lib/pythonx.y/site-packages.

**Comment by tdsmith** [comment]
I agree this bug is resolved; thanks again, @iMichka, for your hard work on this issue!

**Comment by dmwelch** [comment]
@rambalachandran If you're using virtualenvwrapper:
```sh
workon my_env
add2virtualenv /usr/local/opt/vtk/lib/python<x.y>/site-packages  #where <x.y> == 2.7, 3.3, etc.
```
