### ISSUE TITLE
Octave Fortran Link issue

### ISSUE THREAD

**Issue by parthiyban** [Homebrew/homebrew-science#3723]
installed octave using home-brew.
octave
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/Cellar/octave/4.0.2_3/libexec/octave/4.0.2/exec/x86_64-apple-darwin14.5.0/octave-gui
  Reason: image not found
octave exited with signal 5

- Ran `brew update` 
- Ran `brew doctor`
- Ran brew reinstall qrupdate --build-from-source
reinstalled octave
gfortran install path is ../Cellar/gcc/6.1.0/bin/gfortran whereas octave is referring to a different location
/usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib

### Bug reports / build errors:

readlink `which gfortran`
../Cellar/gcc/6.1.0/bin/gfortran

**Comment by vladakolic** [comment]
I have the same issue. `/usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib` does not exist on my machine, it is located under /`usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib`. Probably just need to change some reference somewhere?

**Comment by dpo** [comment]
Fixed by #3724.

**Comment by olalonde** [comment]
Still having this issue... Tried a bunch of stuff:

```
~$ octave
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/opt/arpack/libexec/lib/libarpack.2.dylib
  Reason: image not found
octave exited with signal 6
~$ readlink $(which gfortran)
../Cellar/gcc/6.3.0_1/bin/gfortran
~$ brew reinstall qrupdate
==> Reinstalling homebrew/science/qrupdate
==> Downloading https://homebrew.bintray.com/bottles-science/qrupdate-1.1.2_4.sierra.bottle.1.tar.gz
Already downloaded: /Users/olalonde/Library/Caches/Homebrew/qrupdate-1.1.2_4.sierra.bottle.1.tar.gz
==> Pouring qrupdate-1.1.2_4.sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/qrupdate/1.1.2_4: 8 files, 337.9KB
~$ octave
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/opt/arpack/libexec/lib/libarpack.2.dylib
  Reason: image not found
octave exited with signal 6
~$ ll /usr/local/opt/gcc/lib/gcc/
total 0
drwxr-xr-x   3 olalonde  admin   102B Dec 21 01:56 .
drwxr-xr-x   3 olalonde  admin   102B Dec 21 01:56 ..
drwxr-xr-x  52 olalonde  admin   1.7K Mar 22 13:09 6
~
```

For some reason it tries to load a library in `/usr/local/opt/gcc/lib/gcc/5` which doesn't exist (5 should be 6).

**Comment by JCount** [comment]
Have you tried reinstalling `arpack`?

**Comment by olalonde** [comment]
@JCount yes but didn't work. Only thing that worked was using the `--build-from-source` flag (https://github.com/Homebrew/homebrew-science/issues/4972#issuecomment-288533210)

**Comment by JCount** [comment]
@olalonde That would have been the next thing I would have suggested. It's just a bit strange because I loooked at the contents of the bottle itself, everything seemed to be in order. Perhaps the bottle needs to be rebuilt... Once I am behind my Mac again I'll take a look at that, so others won't continue to have this problem. In any case, I'm glad you found a solution.
