### ISSUE TITLE
regression: brew upgrade homebrew/science/opencv fails

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-science#4399]
(used to work)
ubuntu 16.04:
brew gist-logs homebrew/science/opencv
https://gist.github.com/5949e4f2a2b1e304e82dc28b83514239

ubuntu 14.04:
brew gist-logs homebrew/science/opencv
https://gist.github.com/5ed499c3abfd54df8871fa3206dec251

==> Upgrading homebrew/science/opencv

```
==> Upgrading homebrew/science/opencv
==> Downloading https://github.com/opencv/opencv/archive/2.4.13.tar.gz
Already downloaded: /home/timothee/.cache/Homebrew/opencv-2.4.13.tar.gz
Usage: /home/timothee/.linuxbrew/bin/python-config [--prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--help]
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/timothee/.linuxbrew/Cellar/op
==> make
Last 15 lines from /home/timothee/.cache/Homebrew/Logs/opencv/02.make:
[100%] Built target opencv_perf_stitching
[100%] Linking CXX executable ../../bin/opencv_test_contrib
cd /tmp/opencv-20161004-8360-8p02mm/opencv-2.4.13/macbuild/modules/contrib && /home/timothee/.linuxbrew/Cellar/cmake/3.6.2/bin/cmake -E cmake_link_script CMakeFiles/opencv_test_contrib.dir/link.txt --verbose=1
/home/timothee/.linuxbrew/bin/g++-5   -Os -w -pipe -march=native    -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-array-bounds -Wno-aggressive-loop-optimizations -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections -DNDEBUG  -DNDEBUG   -L/home/timothee/.linuxbrew/lib -Wl,--dynamic-linker=/home/timothee/.linuxbrew/lib/ld.so -Wl,-rpath,/home/timothee/.linuxbrew/lib    CMakeFiles/opencv_test_contrib.dir/test/test_main.cpp.o  -o ../../bin/opencv_test_contrib -rdynamic ../../lib/libopencv_contrib.so.2.4.13 ../../lib/libopencv_ts.a -ldl -lm -lpthread -lrt ../../lib/libopencv_nonfree.so.2.4.13 ../../lib/libopencv_gpu.so.2.4.13 ../../lib/libopencv_legacy.so.2.4.13 ../../lib/libopencv_ml.so.2.4.13 ../../lib/libopencv_objdetect.so.2.4.13 ../../lib/libopencv_photo.so.2.4.13 ../../lib/libopencv_calib3d.so.2.4.13 ../../lib/libopencv_features2d.so.2.4.13 ../../lib/libopencv_flann.so.2.4.13 ../../lib/libopencv_highgui.so.2.4.13 ../../lib/libopencv_video.so.2.4.13 ../../lib/libopencv_imgproc.so.2.4.13 ../../lib/libopencv_core.so.2.4.13 -ldl -lm -lpthread -lrt -Wl,-rpath,/home/timothee/.linuxbrew/Cellar/opencv/2.4.13_3/lib
make[2]: Leaving directory '/tmp/opencv-20161004-8360-8p02mm/opencv-2.4.13/macbuild'
[100%] Built target opencv_test_contrib
[100%] Linking CXX executable ../../bin/opencv_perf_gpu
cd /tmp/opencv-20161004-8360-8p02mm/opencv-2.4.13/macbuild/modules/gpu && /home/timothee/.linuxbrew/Cellar/cmake/3.6.2/bin/cmake -E cmake_link_script CMakeFiles/opencv_perf_gpu.dir/link.txt --verbose=1
/home/timothee/.linuxbrew/bin/g++-5   -Os -w -pipe -march=native    -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-array-bounds -Wno-aggressive-loop-optimizations -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections -DNDEBUG  -DNDEBUG   -L/home/timothee/.linuxbrew/lib -Wl,--dynamic-linker=/home/timothee/.linuxbrew/lib/ld.so -Wl,-rpath,/home/timothee/.linuxbrew/lib    CMakeFiles/opencv_perf_gpu.dir/perf/perf_calib3d.cpp.o CMakeFiles/opencv_perf_gpu.dir/perf/perf_core.cpp.o CMakeFiles/opencv_perf_gpu.dir/perf/perf_denoising.cpp.o CMakeFiles/opencv_perf_gpu.dir/perf/perf_features2d.cpp.o CMakeFiles/opencv_perf_gpu.dir/perf/perf_filters.cpp.o CMakeFiles/opencv_perf_gpu.dir/perf/perf_imgproc.cpp.o CMakeFiles/opencv_perf_gpu.dir/perf/perf_labeling.cpp.o CMakeFiles/opencv_perf_gpu.dir/perf/perf_main.cpp.o CMakeFiles/opencv_perf_gpu.dir/perf/perf_matop.cpp.o CMakeFiles/opencv_perf_gpu.dir/perf/perf_objdetect.cpp.o CMakeFiles/opencv_perf_gpu.dir/perf/perf_video.cpp.o  -o ../../bin/opencv_perf_gpu -rdynamic ../../lib/libopencv_gpu.so.2.4.13 ../../lib/libopencv_ts.a -ldl -lm -lpthread -lrt ../../lib/libopencv_legacy.so.2.4.13 ../../lib/libopencv_ml.so.2.4.13 ../../lib/libopencv_objdetect.so.2.4.13 ../../lib/libopencv_photo.so.2.4.13 ../../lib/libopencv_calib3d.so.2.4.13 ../../lib/libopencv_features2d.so.2.4.13 ../../lib/libopencv_flann.so.2.4.13 ../../lib/libopencv_highgui.so.2.4.13 ../../lib/libopencv_video.so.2.4.13 ../../lib/libopencv_imgproc.so.2.4.13 ../../lib/libopencv_core.so.2.4.13 -ldl -lm -lpthread -lrt -Wl,-rpath,/home/timothee/.linuxbrew/Cellar/opencv/2.4.13_3/lib
make[2]: Leaving directory '/tmp/opencv-20161004-8360-8p02mm/opencv-2.4.13/macbuild'
[100%] Built target opencv_perf_gpu
make[2]: Leaving directory '/tmp/opencv-20161004-8360-8p02mm/opencv-2.4.13/macbuild'
make[1]: *** [CMakeFiles/Makefile2:5623: modules/python/CMakeFiles/opencv_python.dir/all] Error 2
make[1]: Leaving directory '/tmp/opencv-20161004-8360-8p02mm/opencv-2.4.13/macbuild'
make: *** [Makefile:164: all] Error 2
```

**Comment by RedAthens** [comment]
I have also met this error.

**Comment by D-X-Y** [comment]
I use homebrew to upgrade opencv.
==> Upgrading homebrew/science/opencv
==> Downloading https://github.com/opencv/opencv/archive/2.4.13.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/opencv/2.4.13_3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FR
==> make

Also meet a similar error...  :(

**Comment by fabe85** [comment]
I have a similar error with macOS 10.12:

`==> Installing opencv from homebrew/science
==> Downloading https://github.com/opencv/opencv/archive/2.4.13.tar.gz
Already downloaded: /Users/fabian/Library/Caches/Homebrew/opencv-2.4.13.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
==> make
Last 15 lines from /Users/fabian/Library/Logs/Homebrew/opencv/02.make:
make[1]: *** Waiting for unfinished jobs....
[ 15%] Building CXX object modules/video/CMakeFiles/opencv_video.dir/src/optflowgf.cpp.o
cd /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/modules/video && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DCVAPI_EXPORTS -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/perf -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/calib3d/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/features2d/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/highgui/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/imgproc/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/flann/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/core/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/ts/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/modules/video -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/src -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/test -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild -isystem /usr/local/include/eigen3  -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-array-bounds -Wno-aggressive-loop-optimizations -fdiagnostics-show-option -Wno-long-long -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -msse3 -mssse3 -msse4.1 -DNDEBUG  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fPIC   -o CMakeFiles/opencv_video.dir/src/optflowgf.cpp.o -c /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/src/optflowgf.cpp
[ 16%] Building CXX object modules/video/CMakeFiles/opencv_video.dir/src/simpleflow.cpp.o
cd /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/modules/video && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DCVAPI_EXPORTS -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/perf -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/calib3d/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/features2d/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/highgui/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/imgproc/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/flann/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/core/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/ts/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/modules/video -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/src -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/test -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild -isystem /usr/local/include/eigen3  -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-array-bounds -Wno-aggressive-loop-optimizations -fdiagnostics-show-option -Wno-long-long -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -msse3 -mssse3 -msse4.1 -DNDEBUG  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fPIC   -o CMakeFiles/opencv_video.dir/src/simpleflow.cpp.o -c /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/src/simpleflow.cpp
[ 16%] Building CXX object modules/video/CMakeFiles/opencv_video.dir/src/tvl1flow.cpp.o
cd /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/modules/video && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DCVAPI_EXPORTS -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/perf -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/calib3d/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/features2d/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/highgui/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/imgproc/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/flann/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/core/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/ts/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/modules/video -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/src -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/test -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild -isystem /usr/local/include/eigen3  -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-array-bounds -Wno-aggressive-loop-optimizations -fdiagnostics-show-option -Wno-long-long -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -msse3 -mssse3 -msse4.1 -DNDEBUG  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fPIC   -o CMakeFiles/opencv_video.dir/src/tvl1flow.cpp.o -c /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/src/tvl1flow.cpp
[ 16%] Building CXX object modules/video/CMakeFiles/opencv_video.dir/src/video_init.cpp.o
cd /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/modules/video && /usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -DCVAPI_EXPORTS -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/perf -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/calib3d/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/features2d/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/highgui/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/imgproc/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/flann/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/core/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/ts/include -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/modules/video -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/src -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/test -I/tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild -isystem /usr/local/include/eigen3  -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-array-bounds -Wno-aggressive-loop-optimizations -fdiagnostics-show-option -Wno-long-long -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -msse3 -mssse3 -msse4.1 -DNDEBUG  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fPIC   -o CMakeFiles/opencv_video.dir/src/video_init.cpp.o -c /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/modules/video/src/video_init.cpp
[ 16%] Linking CXX shared library ../../lib/libopencv_video.dylib
cd /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/modules/video && /usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_link_script CMakeFiles/opencv_video.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++     -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-array-bounds -Wno-aggressive-loop-optimizations -fdiagnostics-show-option -Wno-long-long -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -msse3 -mssse3 -msse4.1 -DNDEBUG  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 2.4.0 -current_version 2.4.13 -o ../../lib/libopencv_video.2.4.13.dylib -install_name /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/lib/libopencv_video.2.4.dylib CMakeFiles/opencv_video.dir/src/bgfg_gaussmix.cpp.o CMakeFiles/opencv_video.dir/src/bgfg_gaussmix2.cpp.o CMakeFiles/opencv_video.dir/src/bgfg_gmg.cpp.o CMakeFiles/opencv_video.dir/src/camshift.cpp.o CMakeFiles/opencv_video.dir/src/kalman.cpp.o CMakeFiles/opencv_video.dir/src/lkpyramid.cpp.o CMakeFiles/opencv_video.dir/src/motempl.cpp.o CMakeFiles/opencv_video.dir/src/optflowgf.cpp.o CMakeFiles/opencv_video.dir/src/simpleflow.cpp.o CMakeFiles/opencv_video.dir/src/tvl1flow.cpp.o CMakeFiles/opencv_video.dir/src/video_init.cpp.o ../../lib/libopencv_imgproc.2.4.13.dylib ../../lib/libopencv_core.2.4.13.dylib 
cd /tmp/opencv-20161018-44531-366lbf/opencv-2.4.13/macbuild/modules/video && /usr/local/Cellar/cmake/3.6.2/bin/cmake -E cmake_symlink_library ../../lib/libopencv_video.2.4.13.dylib ../../lib/libopencv_video.2.4.dylib ../../lib/libopencv_video.dylib
[ 16%] Built target opencv_video
make: *** [all] Error 2
`

**Comment by dpo** [comment]
See https://github.com/Homebrew/homebrew-science/pull/4336

**Comment by dpo** [comment]
Should be fixed now.

**Comment by timotheecour** [comment]
sorry @dpo but `brew install homebrew/science/opencv` is still broken
brew gist-logs homebrew/science/opencv
https://gist.github.com/5b5e4b60c929eb784533b320dc989aa0

**Comment by chitrang6** [comment]
I ama having the same issue


video.2.4.dylib ../../lib/libopencv_video.dylib
[ 15%] Built target opencv_video
make: *** [all] Error 2

**Comment by timotheecour** [comment]
NOTE: `brew reinstall -v opencv --HEAD --without-python` did work! progress....

**Comment by timotheecour** [comment]
found the root cause and submitted a PR
