### ISSUE TITLE
Pymol crashes on startup

### ISSUE THREAD

**Issue by mesalas** [Homebrew/homebrew-science#5505]
#### Brief summary of issue:
Pymol crashes on stratup main window visible for lesses than a sec
terminal output:

`$pymol`:
               
    PyMOL(TM) Molecular Graphics System, Version 1.8.4.0.
    Copyright (c) Schrodinger, LLC.
    All Rights Reserved.
 
    Created by Warren L. DeLano, Ph.D. 
 
    PyMOL is user-supported open-source software.  Although some versions
    are freely available, PyMOL is not in the public domain.
 
    If PyMOL is helpful in your work or study, then please volunteer 
    support for our ongoing efforts to create open and affordable scientific
    software by purchasing a PyMOL Maintenance and/or Support subscription.

    More information can be found at "http://www.pymol.org".
 
    Enter "help" for a list of commands.
    Enter "help <command-name>" for information on a specific command.

    Hit ESC anytime to toggle between text and graphics.
    
    Detected OpenGL version 2.0 or greater. Shaders available.
    Detected GLSL version 1.20.
    OpenGL graphics engine:
    GL_VENDOR:   Intel Inc.
    GL_RENDERER: Intel(R) Iris(TM) Graphics 6100
    GL_VERSION:  2.1 INTEL-10.18.65
    /usr/local/bin/pymol: line 4: 11399 Abort trap: 6           "/usr/local/opt/python/bin/python2.7" "/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/__init__.py" "$@"

When installing homebrew complains that pymol wants dupes/tcl-tk and npt tcl-tk

    Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk

I have tried to install the regular tcl-tk and the installing pymol with --ignore-dependencies (making sure that i had installed the deps. manually) 

#### The complete command that you issued:
`pymol`
#### Gist with output of `brew doctor`:
`brew doctor`:

    Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk
    Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk
    Your system is ready to brew.

#### Link output by `brew gist-logs <formula>`:
brew gist-logs pymol:

Error: No logs.

#### Output of `brew config`:
`brew config`:

    HOMEBREW_VERSION: 1.1.13
    ORIGIN: https://github.com/Homebrew/brew
    HEAD: 46f6dc4c93b96abd528c3a0a808a5ca5a795c7f3
    Last commit: 11 days ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: d89bd024e3a14f4ce34a60825e3afc72913b4a51
    Core tap last commit: 35 minutes ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local/Homebrew
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: quad-core 64-bit broadwell
    Homebrew Ruby: 2.0.0-p648
    Clang: 8.1 build 802
    Git: 2.11.0 => /Library/Developer/CommandLineTools/usr/bin/git
    Perl: /usr/bin/perl
    Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
    Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    Java: N/A
    macOS: 10.12-x86_64
    Xcode: N/A
    CLT: 8.3.2.0.1.1492020469
    X11: 2.7.11 => /opt/X11

**Comment by iMichka** [comment]
Thanks for reporting. I am working on a fix here: #5483

**Comment by mesalas** [comment]
Thanks for reply. Just for clarity, I did not fix the problem by installing tcl-tk nor have I found that that is the actual cause of the problem. 

I'll be ready to test when you are done.

**Comment by kuanlinhuang** [comment]
Exactly the same problem looking forward to the fix.

**Comment by konczbenedek** [comment]
Exactly the same problem looking forward to the fix.

**Comment by tdsmith** [comment]
Does `brew reinstall -s pymol` help? Is there a crash log you can share?

**Comment by foldager** [comment]
I have exactly the same problem, and `brew reinstall -s pymol` does not help.

I looked a bit around to find out what was crashing. The crash happens when importing `/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/rpc.py`

I haven't looked more into it though.

**Comment by konczbenedek** [comment]
I can share this: https://gist.github.com/konczbenedek/59249ac073e507255345002b84b474b7. I don't know if it helps. Where sould I look for the crash log? I only get Apples report. 

During clean-install of pymol with brew, it stops after installing tcl-tk and python dependencies, and won't finish with pymol (Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk last message). Than you have to manually restart the installation.

**Comment by tdsmith** [comment]
Apple's report is what I'm looking for.

**Comment by foldager** [comment]
I get this report
[crash report.txt](https://github.com/Homebrew/homebrew-science/files/1021282/crash.report.txt)

**Comment by konczbenedek** [comment]
For me: https://gist.github.com/konczbenedek/af5571c04e5cc72f7e3ff7158e6903e3

**Comment by romainstuder** [comment]
Hi all,

I still haven't found a way to install PyMOL on my Mac with Homebrew. And I also get the "Abort trap: 6" while starting PyMol.

But I don't think the problem is from PyMOL. It is more due to Tcl/Tk release 8.6.6: 
 
tclsh
% puts $tcl_version
8.6
% info patchlevel
8.6.6

And in Python 2.7.13:
python
Python 2.7.13 (default, May 30 2017, 16:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Tkinter
>>> Tkinter._test()
Abort trap: 6

=> This problem doesn't occur with Tcl/Tk 8.5.18 from ActiveTclTk:
https://stackoverflow.com/questions/43618828/simple-tkinter-program-with-abort-trap-6-error
https://github.com/Homebrew/homebrew-core/issues/12114

But if I tried to install PyMOL in an alternative way, I don't get the menu windows, only the 3D window.

**Comment by richardreeve** [comment]
@romainstuder I don't know what you mean by "if I tried to install PyMOL in an alternative way", but I've found that temporarily [installing](https://pymolwiki.org/index.php/MAC_Install#Open-Source_PyMOL) pymol via macports seems to work fine for the time being.

**Comment by iMichka** [comment]
Basically brewed python 2 and 3 are hit by this (I hope the errors are the same); the symptoms are equivalent though:
https://github.com/Homebrew/homebrew-core/issues/12808
https://github.com/Homebrew/homebrew-core/issues/12114

**Comment by fsimkovic** [comment]
Encountered the same issue, what worked for me was
```bash
$> xcode-select --install
$> brew prune
$> brew uninstall python
$> brew install python --with-tcl-tk --enable-threads --with-x11
$> brew install glew
$> brew install --ignore-dependencies homebrew/science/pymol
```

**Comment by romainstuder** [comment]
Thanks for your help. But this doesn't work for me. I still get this "Abort trap: 6" error. It is related to tcl-tk.

**Comment by fsimkovic** [comment]
Try the following: ``brew uninstall tcl-tk``.

**Comment by rbf22** [comment]
Not really sure that this solution works. I tried it and there are a number of problems:

Warning: python: this formula has no --enable-threads option so it will be ignored!
Warning: python: this formula has no --with-x11 option so it will be ignored!

**Comment by iMichka** [comment]
Please stop posting here. **Nobody is actually working on this**; the problem lies somewhere deep in Python and Tcl-TK. So until anybody finds the root cause, nothing is going to happen here.

**Comment by rbf22** [comment]
I come in peace. The last post that is shown on this issue suggests a fix that is does not work. Maybe you should remove that post as well (aka fsimkovic). Have a nice day.

**Comment by iMichka** [comment]
Please, don't take it personally. That was not the intent. I am just trying to slow down the flow of incoming messages here. I would like to get this fixed too, but somebody needs to dive deep into the tcl-tk python build process.

**Comment by rbf22** [comment]
You might like to take a quick look at the macports version of tcl-tk. I believe that they have managed to build pymol that works on top of tcl-tk 8.6.6.

**Comment by telamonian** [comment]
I've submitted a pull request (#15950) to core with a fix for #12114 and #12808. Long story short, tcltk 8.6.6 has a zillion OS X specific bugs that the tcltk devs fixed in 8.6.7. Since there's still no official release on the horizon, I updated the `tcl-tk` formula with a `--devel` option, so now if you install tcltk using the updated formula with:

    brew install tcl-tk --with-threads --devel

Now, any python/tkinter/pymol you build against the brewed tcltk should just work, or at least it does for me.

**Comment by telamonian** [comment]
### small disclaimer

When installing pymol, I did run into a problem where pymol kept building against the system python. In the end, in order for pymol to use the brewed python, I had to change a line in the `pymol` formula, from:

    system "python", "-s", "setup.py", "install",

to

    system "python2", "-s", "setup.py", "install",

This had nothing to do with tcltk, but was caused instead by the recent breaking change in how homebrew handles the path for python 2 (see #15746). The homebrew/core devs are now telling everyone to add `/usr/local/opt/python/libexec/bin` to the front of their PATH if they want `python ` to point to the brewed python. But even this did nothing to fix the pymol build, as it seems like superenv throws that part of the PATH out. 

You may or may not run into this problem yourself depending on exactly what your recent python installation history has been like.

**Comment by telamonian** [comment]
#### BIG DISCLAIMER

There's a big catch. Pymol will build and run just fine with tcltk 8.6.7, and the main pymol viewer window also works just fine, but the external gui (the window with all of the menus and command buttons) is completely broken. I've tried a whole bunch of things, but not for love nor money have I been able to get the external gui to show up.

In fact, through many hours of experimentation, the only way that I could manage to get a completely working build of pymol was by rebuilding tcltk with support for x11 instead of the now default Aqua. From the few mentions of the topic in the Pymol docs/wiki, I gather that although Schroedinger did in fact add Aqua support to Pymol, they kept it back in the closed source incentive version (or maybe even just in a couple of specific build) and never shared it with the open source branch.

I'm not sure what to do about this as the homebrew-core devs seem completely hostile to the idea of reenabling the `--with-x11` option in the `tcl-tk` formula. No joke, I submitted a pull request that  reenabled the `--with-x11` option and ilovezfs closed it within literally 15 seconds. They just really don't like x11.

Maybe if we can convince them that removing x11 support from tcltk irreversibly breaks some import software (pymol included), the core devs will allow it back in? The only other (extremely terrible) idea that I can think of is for homebrew-science to maintain it's own version the `tcl-tk` formula, something along the lines of `homebrew/science/tcl-tk-x11`.

**Comment by jarvist** [comment]
Just a quick note, that a currently 'broken' pymol installation can be made to work without the GUI as a '(h)elper' application with 'pymol -h'. This is enough to view a molecule with the default line drawing.

**Comment by telamonian** [comment]
Oh no, don't get me wrong. The visualization part of the GUI works perfectly (and looks very pretty), and you can still get access to the right click menu, at least. It's the second GUI window, the one with all of the buttons, the menus, and the somewhat more flexible command prompt, that never appears.

**Comment by jarvist** [comment]
Sorry I wasn't being clear.
Even with the default, 'Abort trap: 6' broken version of Pymol currently in Homebrew master, you can run Pymol without the gui via 'pymol -h'.

**Comment by telamonian** [comment]
Sorry about that, I did understand what you meant the second time I read your comment (which is why I deleted mine).

**Comment by bd712** [comment]
This doesn't seem to work for me, I get an error:

`Error: No devel block is defined for tcl-tk`

Any idea what I can do about this? Thanks!

> I've submitted a pull request (#15950) to core with a fix for #12114 and #12808. Long story short, tcltk 8.6.6 has a zillion OS X specific bugs that the tcltk devs fixed in 8.6.7. Since there's still no official release on the horizon, I updated the tcl-tk formula with a --devel option, so now if you install tcltk using the updated formula with:

>`brew install tcl-tk --with-threads --devel`
>Now, any python/tkinter/pymol you build against the brewed tcltk should just work, or at least it does for me.

**Comment by byamal** [comment]
@bd712 Did you find the solution to that?? I'm having the same issues and tried all listed above but still, it has an issue with this.

**Comment by telamonian** [comment]
My `tcl-tk` pull request ran into some trouble due to some upstream bugs in `homebrew` itself (see Homebrew/homebrew-core#15950). The issue is currently getting resolved, and should be dealt with fairly soon. 

In the meantime if anyone desperately needs pymol for work, leave a message here and I'll post a workaround.

**Comment by telamonian** [comment]
Okay, my pull request has finally been merged. Anyone who wants to install pymol using homebrew should make sure that the `tcl-tk` and `python` formulae are both uninstalled, and then do:

```
brew install tcl-tk --devel
brew install python --with-tcl-tk
brew install pymol
```

If you run into any problems, check my other posts in this thread for possible workarounds.

**Comment by telamonian** [comment]
Sadly though, as long as homebrew's `tcl-tk` only supports Aqua and not X11 pymol's external GUI window is unlikely to work :(

I've been poking around the pymol source trying to figure out why. Normally, pymol uses the Tkinter package to create the external GUI window. Tkinter is built against `tcl-tk`. For whatever reason, when pymol tells Tkinter to open a window, if `tcl-tk` is built with Aqua support instead of X11 support nothing happens. Which is strange, since Aqua Tkinter seems to be capable of opening windows from other python programs. 

I think it has something to do with the way in which the pymol executable is launched. I'll see if I can figure out a fix, but don't get your hopes up.

**Comment by telamonian** [comment]
Soooo... much to my surprise I was able to come up with a patch that fixes well, pretty much everything. Turns out that Pymol and Tkinter Aqua actually can live in harmony with one another. Who knew? 

Though It was still a ridiculous pain in the ass, @ilovezfs.

Anyway, not only does the patch allow for easy use of the external GUI, Pymol seem to crash a lot less (because a lot of the recent crashes were in fact due to Tkinter Aqua issues), and to boot it's also easier to install, since I was able to remove the dependency on a brewed version of `tcl-tk`.

If you're curious, see pull request #6066 for far too many details.

**Comment by ilovezfs** [comment]
>~Though It was still a ridiculous pain in the ass, @ilovezfs.~ Though It did still take a ridiculous quantity of effort, @ilovezfs.

LOL.

**Comment by telamonian** [comment]
> ~~Though It was still a ridiculous pain in the ass, @ilovezfs.~~

And it was, too! 

Though the public forum was not the most gracious place to vent about it, in hindsight. I don't agree with every decision, but I want to make it clear that I have nothing but respect for you and the rest of the homebrew team. brew was a huge boon when I was just starting out as a programmer, and I take a great pleasure in being able to contribute to the project now.

**Comment by telamonian** [comment]
I do think that the funniest thing to come out of this project is that when comparing the Aqua GUI:

![image](https://user-images.githubusercontent.com/2263641/28983521-2d6b242c-7928-11e7-9368-545283782ca6.png)

to the X11 GUI:

![image](https://user-images.githubusercontent.com/2263641/28983660-bef6e066-7928-11e7-944d-da8370975717.png)

the X11 one is definitely prettier!

To be fair, I bet that somebody (not it!) could clean the Aqua version up quite a bit, though the code that sets up the GUI is several thousand lines all by itself.

**Comment by ilovezfs** [comment]
According to the scriptures, all Aqua GUIs are better than all X11 GUIs by their very nature. Only heretics believe otherwise.

**Comment by telamonian** [comment]
I... am not familiar with that particular catechism, but I suppose I will abide :)

**Comment by rcdragon** [comment]
I am having problems with getting the right tcl-tk. Dreaded 404 error. Is the https link is incomplete?
 I enter the command and get

$ **brew install tcl-tk --deve**l
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.7/tcl8.6.7

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading ftp://ftp.tcl.tk/pub/tcl/tcl8_6/tcl8.6.7rc0-src.tar.gz

curl: (19) Given file does not exist
Error: Failed to download resource "tcl-tk"
Download failed: ftp://ftp.tcl.tk/pub/tcl/tcl8_6/tcl8.6.7rc0-src.tar.gz
$

**Comment by ilovezfs** [comment]
It looks like upstream yanked rc0 and posted rc1.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/16428

**Comment by ilovezfs** [comment]
@rcdragon it should be fixed now if you brew update.

**Comment by romainstuder** [comment]
Thanks for the recent development. I managed to install tcl-tk 8.6.7, and run Tk in Python2 without crash.
But I am still not able to run PyMOL, the menu window doesn't open. Did anyone succeed to properly install PyMOL with Homebrew?

**Comment by konczbenedek** [comment]
Can somebody write down the exact steps of installing a working pymol with homebrew?

I have removed both tcl-tk and python, reinstalled them with --devel flag (tcl-tk), and than I installed pymol. Now I don't get anything close to a working version. It states e.g. that I don't have the glew libraries.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 72, in <module>
    import pymol
  File "/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 536, in <module>
    import pymol._cmd
ImportError: dlopen(/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/_cmd.so, 2): Library not loaded: /usr/local/opt/glew/lib/libGLEW.2.0.0.dylib
  Referenced from: /usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/_cmd.so
  Reason: image not found
```

**Comment by telamonian** [comment]
@konczbenedek I can reproduce your bug if I install `pymol` from the current `1.8.4.0` bottle. The issue it seems you're running into is that the bottle is stale, and homebrew's `glew` has had a version bump to `2.1.0` in the time since it was poured. 

Check your glew libs by running `ls /usr/local/opt/glew/lib`. If you see `libGLEW.2.1.0.dylib` in the output, then faking `2.0.0` with a link will fix your issue:
```
ln -s /usr/local/opt/glew/lib/libGLEW.2.1.0.dylib /usr/local/opt/glew/lib/libGLEW.2.0.0.dylib
```
although it might be buggy. 

Also, make sure that you passed the `--with-tcl-tk` argument to `python` when you were installing it.

**Comment by telamonian** [comment]
Alternatively, you could wait a day or two. I have a PR in the works (#6066) that remove the `tcl-tk` dependency and more. It seems like the PR is close to getting accepted, and once it does there'll be a new `pymol` bottle that will more permanently fix your issue.

**Comment by telamonian** [comment]
@romainstuder I'm not sure exactly what's going on with your `pymol`, but if I had to guess you've likely been bitten by a bug related to all of the recent changes in how Homebrew's `python` formula sets up paths.

Try running `vim $(which pymol)`. If the first part of the last line in that script is `/usr/bin/python`, that means that your `pymol` linked against the system `python` instead of the homebrew `python`. Try changing `/usr/bin/python` to `/usr/local/opt/python/bin/python2.7` (or some other valid path to the executable of your homebrew `python`) and that may fix your issue.

**Comment by romainstuder** [comment]
I am not sure either. :D

I tried to install tcl-tk devel, but the link is broken. Because the last release of Tcl/Tk 8.6.7 is now online: https://sourceforge.net/projects/tcl/?source=typ_redirect

Here are the lines to change in the formula:

  stable do
    url "https://downloads.sourceforge.net/project/tcl/Tcl/8.6.7/tcl8.6.7-src.tar.gz"
    mirror "ftp://ftp.tcl.tk/pub/tcl/tcl8_6/tcl8.6.7-src.tar.gz"
    version "8.6.7"
    sha256 "7c6b8f84e37332423cfe5bae503440d88450da8cc1243496249faa5268026ba5"

    resource "tk" do
      url "https://downloads.sourceforge.net/project/tcl/Tcl/8.6.7/tk8.6.7-src.tar.gz"
      mirror "ftp://ftp.tcl.tk/pub/tcl/tcl8_6/tk8.6.7-src.tar.gz"
      version "8.6.7"
      sha256 "061de2a354f9b7c7d04de3984c90c9bc6dd3a1b8377bb45509f1ad8a8d6337aa"
    end
  end


The problem is it works on my local install, but when I tried to install "brew install python --with-tcl-tk" and "brew install pymol", they try to download tcl-tk_8.6.6 instead of using the local install tcl-tk_8.6.7.

It would be good if someone can make the changes to have tcl-tk 8.6.7 in Homebrew. I can also give a try tonight.

**Comment by romainstuder** [comment]
Ok, I update tcl-tk formula to 8.6.7: https://github.com/Homebrew/homebrew-core/blob/master/Formula/tcl-tk.rb

But the Aqua interface seems so buggy with Tkinter. I cannot click on anything. And PyMol doesn't work either.

**Comment by romainstuder** [comment]
I just tried to install the new PyMOL 1.8.6 formula from @telamonian and it works!

`brew install https://raw.githubusercontent.com/telamonian/homebrew-science/77ca037e1b7abadf16d4944c6ba3b0e277598eba/pymol.rb
`
So ready to be incorporated in the main homebrew I guess. Thanks!

**Comment by konczbenedek** [comment]
I have tried both solutions on two different machines. 1). The first version is what @telamonian suggested me on the 9th of August is working pymol starts but the smallar GUI window is frozen. You can not click on anything. But it works opens files etc. This uses the bottled version 1.8.4. 2.) The other version built from source - 1.8.6. opens, both GUI window works, but I can not run pymol in command line mode `pymol -c`. When I try to run the same script on both versions 1. will give you the desired result (aka executes the scrip as charm) and 2. dose nothing, and exits without any error code, the log states this:

```
 PyMOL(TM) Molecular Graphics System, Version 1.8.6.0.
 Copyright (c) Schrodinger, LLC.
 All Rights Reserved.
 
    Created by Warren L. DeLano, Ph.D. 
 
    PyMOL is user-supported open-source software.  Although some versions
    are freely available, PyMOL is not in the public domain.
 
    If PyMOL is helpful in your work or study, then please volunteer 
    support for our ongoing efforts to create open and affordable scientific
    software by purchasing a PyMOL Maintenance and/or Support subscription.

    More information can be found at "http://www.pymol.org".
 
    Enter "help" for a list of commands.
    Enter "help <command-name>" for information on a specific command.

 Hit ESC anytime to toggle between text and graphics.

 Command mode. No graphics front end.
```
Any suggestions?

**Comment by jessequinn** [comment]
Using w install https://raw.githubusercontent.com/telamonian/homebrew-science/77ca037e1b7abadf16d4944c6ba3b0e277598eba/pymol.rb

with update tcl-tk (8.6.7) I receive the following error

comp1:include admin$ pymol
Unable to find application named 'X11'
freeglut failed to open display ':0.0'
 PyMOL: abrupt program termination.

using 1.8.4 pymol I receive the following error:
comp1:include admin$ pymol
Traceback (most recent call last):
  File "/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 72, in <module>
    import pymol
  File "/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/__init__.py", line 536, in <module>
    import pymol._cmd
ImportError: dlopen(/usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/_cmd.so, 2): Library not loaded: /usr/local/opt/glew/lib/libGLEW.2.0.0.dylib
  Referenced from: /usr/local/Cellar/pymol/1.8.4.0/libexec/lib/python2.7/site-packages/pymol/_cmd.so
  Reason: image not found

faking the dylib as suggested:

ln -s /usr/local/opt/glew/lib/libGLEW.2.1.0.dylib /usr/local/opt/glew/lib/libGLEW.2.0.0.dylib

gives the same error as the first situation.

Any ideas?

**Comment by romainstuder** [comment]
Hi jessequinn,

The link from telamonian to install PyMOL 1.8.6 works for me. PyMOL is complaining that it cannot find 'X11'. X11 is actually named Xquartz in MacOSX. 

1) Install Xquartz if it is not installed.
2) Link it to X11: "sudo ln -s /opt/X11/bin/Xquartz /opt/X11/bin/X11"
3) In a new terminal, "which X11" should point to "/opt/X11/bin/X11", and "ls -l /opt/X11/bin/X11" should point to "/opt/X11/bin/Xquartz".
4) Run pymol.

This should normally work.

**Comment by jessequinn** [comment]
which X11 gives this
/opt/X11/bin/X11

but I still get the same error
admin$ pymol
Unable to find application named 'X11'
freeglut failed to open display ':0.0'
 PyMOL: abrupt program termination.

**Comment by romainstuder** [comment]
What about "ls -l /opt/X11/bin/X11"? And if you just type "X11", does anything happen?

Could you also try:

"brew reinstall glew"
"brew install https://raw.githubusercontent.com/telamonian/homebrew-science/77ca037e1b7abadf16d4944c6ba3b0e277598eba/pymol.rb"

**Comment by CarmenSC** [comment]
Hi everyone!, I tried @telamonian solution but it didn't works :(

Hope you can help me.


$brew install https://raw.githubusercontent.com/telamonian/homebrew-science/77ca037e1b7abadf16d4944c6ba3b0e277598eba/pymol.rb
######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/pymol-1.8.6.0.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "pymol"
Download failed: https://homebrew.bintray.com/bottles/pymol-1.8.6.0.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://downloads.sourceforge.net/project/pymol/pymol/1.8/pymol-v1.8.6.0.tar.bz2
Already downloaded: /Users/Carmen/Library/Caches/Homebrew/pymol-1.8.6.0.tar.bz2
==> Downloading https://github.com/telamonian/pymol/compare/1.8.6.0...1.8.6.0_-_osx_gui_fix_-_release.diff
Already downloaded: /Users/Carmen/Library/Caches/Homebrew/pymol--patch-9468d379b6c0bcf819fce7f758d24bd2656508da4a7fda82af804649cc2e5bf3.diff
==> Patching
==> Applying 1.8.6.0...1.8.6.0_-_osx_gui_fix_-_release.diff
patching file modules/pmg_tk/PMGApp.py
patching file modules/pmg_tk/__init__.py
patching file modules/pymol/__init__.py
==> python -s setup.py install --bundled-pmw --install-scripts=/usr/local/Cellar/pymol/1.8.6.0/libexec/bin --install-lib=/usr/local/Ce
Last 15 lines from /Users/Carmen/Library/Logs/Homebrew/pymol/01.python:
2017-09-10 22:21:32 +0100

python
-s
setup.py
install
--bundled-pmw
--install-scripts=/usr/local/Cellar/pymol/1.8.6.0/libexec/bin
--install-lib=/usr/local/Cellar/pymol/1.8.6.0/libexec/lib/python2.7/site-packages

Your PYTHONPATH points to a site-packages dir for Python 3.x but you are running Python 2.x!
     PYTHONPATH is currently: "/usr/local/lib/python3.6/site-packages"
     You should `unset PYTHONPATH` to fix this.

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Migrate popular formulae from Homebrew/homebrew-* taps https://github.com/Homebrew/homebrew-core/issues/15619

**Comment by carlosfamilia** [comment]
Hi,

I tried the Pymol version from telamonian, but I am getting the following:

brew install https://raw.githubusercontent.com/telamonian/homebrew-science/77ca037e1b7abadf16d4944c6ba3b0e277598eba/pymol.rb
######################################################################## 100.0%
==> Downloading https://downloads.sourceforge.net/project/pymol/pymol/1.8/pymol-
Already downloaded: /Users/familia/Library/Caches/Homebrew/pymol-1.8.6.0.tar.bz2
==> Downloading https://github.com/telamonian/pymol/compare/1.8.6.0...1.8.6.0_-_
Already downloaded: /Users/familia/Library/Caches/Homebrew/pymol--patch-9468d379b6c0bcf819fce7f758d24bd2656508da4a7fda82af804649cc2e5bf3.diff
==> Patching
==> Applying 1.8.6.0...1.8.6.0_-_osx_gui_fix_-_release.diff
patching file modules/pmg_tk/PMGApp.py
patching file modules/pmg_tk/__init__.py
patching file modules/pymol/__init__.py
==> python -s setup.py install --bundled-pmw --install-scripts=/usr/local/Cellar
Last 15 lines from /Users/familia/Library/Logs/Homebrew/pymol/01.python:
In file included from layer1/Basis.h:20:
In file included from layer0/Map.h:24:
In file included from layer0/Vector.h:23:
/usr/include/math.h:712:9: warning: 'MAXFLOAT' macro redefined [-Wmacro-redefined]
#define MAXFLOAT    0x1.fffffep+127f
        ^
layer0/Base.h:51:9: note: previous definition is here
#define MAXFLOAT FLT_MAX
        ^
1 warning generated.
clang++ -Wno-nullability-completeness -std=c++0x -D_PYMOL_LIBPNG -D_PYMOL_INLINE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_FREETYPE -DNO_MMLIBS -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/include -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -I/usr/local/include -I/usr/local/include/freetype2 -I/usr/include -I/usr/include/libxml2 -I/usr/X11/include -I/usr/X11/include/freetype2 -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/tcl-tk/include -I/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c layer2/ObjectGroup.cpp -o build/temp.macosx-10.13-x86_64-2.7/layer2/ObjectGroup.o -Wno-write-strings -Wno-unused-function -Wno-char-subscripts -ffast-math -funroll-loops -fcommon
clang++ -Wno-nullability-completeness -std=c++0x -D_PYMOL_LIBPNG -D_PYMOL_INLINE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_FREETYPE -DNO_MMLIBS -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/include -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -I/usr/local/include -I/usr/local/include/freetype2 -I/usr/include -I/usr/include/libxml2 -I/usr/X11/include -I/usr/X11/include/freetype2 -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/tcl-tk/include -I/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c layer2/MolV3000.cpp -o build/temp.macosx-10.13-x86_64-2.7/layer2/MolV3000.o -Wno-write-strings -Wno-unused-function -Wno-char-subscripts -ffast-math -funroll-loops -fcommon
13 errors generated.
clang++ -Wno-nullability-completeness -std=c++0x -D_PYMOL_LIBPNG -D_PYMOL_INLINE -D_PYMOL_VMD_PLUGINS -D_HAVE_LIBXML -DMMTF_MSGPACK_USE_CPP11 -D_PYMOL_FREETYPE -DNO_MMLIBS -Iov/src -Ilayer0 -Ilayer1 -Ilayer2 -Ilayer3 -Ilayer4 -Ilayer5 -Imodules/cealign/src -Ibuild/generated -Icontrib/uiuc/plugins/include -Icontrib/uiuc/plugins/molfile_plugin/src -Icontrib/mmtf-c -I/usr/local/include -I/usr/local/include/freetype2 -I/usr/include -I/usr/include/libxml2 -I/usr/X11/include -I/usr/X11/include/freetype2 -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/tcl-tk/include -I/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c layer2/RepNonbondedSphere.cpp -o build/temp.macosx-10.13-x86_64-2.7/layer2/RepNonbondedSphere.o -Wno-write-strings -Wno-unused-function -Wno-char-subscripts -ffast-math -funroll-loops -fcommon
error: command 'clang++' failed with exit status 1

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Migrate popular formulae from Homebrew/homebrew-* taps https://github.com/Homebrew/homebrew-core/issues/15619


Any ideas?
Thanks

**Comment by iMichka** [comment]
`pymol` has been removed from homebrew-science; see https://github.com/Homebrew/homebrew-science/pull/6066#issuecomment-339787789 for an explanation. Closing here.

**Comment by konczbenedek** [comment]
this is really sad
