### ISSUE TITLE
geant4 error, please fix

### ISSUE THREAD

**Issue by cxwx** [Homebrew/homebrew-science#6291]
homebrew installed geant4

when source /usr/loacl/bin/geant4.sh

error:
   -bash: cd: /usr/local/bin/../share/Geant4-10.3.1/data/PhotonEvaporation4.3.2: No such file or directory
-bash: cd: /usr/local/bin/../share/Geant4-10.3.1/data/RadioactiveDecay5.1.1: No such file or directory 

I found PhotonEvaporation4.3 and RadioactiveDecay5.1 instead

could someone fix it

**Comment by davidchall** [comment]
@cxwx this should now be fixed

**Comment by jonchang** [comment]
Resolved by #6410

**Comment by tiwariPC** [comment]
I am still getting this problem, is there some extra set of commands to apply the above fix?
